//! AUTO-GENERATED link stubs for the QuickJS backend (placeholder).
#![allow(non_snake_case)]

#[unsafe(no_mangle)] pub extern "C" fn cppgc__heap__collect_garbage_for_testing() { unimplemented!("cppgc__heap__collect_garbage_for_testing") }
#[unsafe(no_mangle)] pub extern "C" fn cppgc__heap__enable_detached_garbage_collections_for_testing() { unimplemented!("cppgc__heap__enable_detached_garbage_collections_for_testing") }
#[unsafe(no_mangle)] pub extern "C" fn cppgc__initialize_process() { unimplemented!("cppgc__initialize_process") }
#[unsafe(no_mangle)] pub extern "C" fn cppgc__make_garbage_collectable() { unimplemented!("cppgc__make_garbage_collectable") }
#[unsafe(no_mangle)] pub extern "C" fn cppgc__Member__CONSTRUCT() { unimplemented!("cppgc__Member__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn cppgc__Member__DESTRUCT() { unimplemented!("cppgc__Member__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn cppgc__Persistent__CONSTRUCT() { unimplemented!("cppgc__Persistent__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn cppgc__Persistent__DESTRUCT() { unimplemented!("cppgc__Persistent__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn cppgc__Persistent__Get() { unimplemented!("cppgc__Persistent__Get") }
#[unsafe(no_mangle)] pub extern "C" fn cppgc__shutdown_process() { unimplemented!("cppgc__shutdown_process") }
#[unsafe(no_mangle)] pub extern "C" fn cppgc__Visitor__Trace__TracedReference() { unimplemented!("cppgc__Visitor__Trace__TracedReference") }
#[unsafe(no_mangle)] pub extern "C" fn cppgc__WeakMember__CONSTRUCT() { unimplemented!("cppgc__WeakMember__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn cppgc__WeakMember__DESTRUCT() { unimplemented!("cppgc__WeakMember__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__base64_length_from_binary() { unimplemented!("simdutf__base64_length_from_binary") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__base64_to_binary() { unimplemented!("simdutf__base64_to_binary") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__binary_to_base64() { unimplemented!("simdutf__binary_to_base64") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_latin1_to_utf16le() { unimplemented!("simdutf__convert_latin1_to_utf16le") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_latin1_to_utf8() { unimplemented!("simdutf__convert_latin1_to_utf8") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_utf16be_to_utf8() { unimplemented!("simdutf__convert_utf16be_to_utf8") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_utf16le_to_latin1() { unimplemented!("simdutf__convert_utf16le_to_latin1") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_utf16le_to_utf8() { unimplemented!("simdutf__convert_utf16le_to_utf8") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_utf16le_to_utf8_with_errors() { unimplemented!("simdutf__convert_utf16le_to_utf8_with_errors") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_utf32_to_utf8() { unimplemented!("simdutf__convert_utf32_to_utf8") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_utf8_to_latin1() { unimplemented!("simdutf__convert_utf8_to_latin1") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_utf8_to_latin1_with_errors() { unimplemented!("simdutf__convert_utf8_to_latin1_with_errors") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_utf8_to_utf16be() { unimplemented!("simdutf__convert_utf8_to_utf16be") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_utf8_to_utf16le() { unimplemented!("simdutf__convert_utf8_to_utf16le") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_utf8_to_utf16le_with_errors() { unimplemented!("simdutf__convert_utf8_to_utf16le_with_errors") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_utf8_to_utf32() { unimplemented!("simdutf__convert_utf8_to_utf32") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_valid_utf16le_to_utf8() { unimplemented!("simdutf__convert_valid_utf16le_to_utf8") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_valid_utf8_to_latin1() { unimplemented!("simdutf__convert_valid_utf8_to_latin1") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__convert_valid_utf8_to_utf16le() { unimplemented!("simdutf__convert_valid_utf8_to_utf16le") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__count_utf16be() { unimplemented!("simdutf__count_utf16be") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__count_utf16le() { unimplemented!("simdutf__count_utf16le") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__count_utf8() { unimplemented!("simdutf__count_utf8") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__detect_encodings() { unimplemented!("simdutf__detect_encodings") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__latin1_length_from_utf8() { unimplemented!("simdutf__latin1_length_from_utf8") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__maximal_binary_length_from_base64() { unimplemented!("simdutf__maximal_binary_length_from_base64") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__utf16_length_from_utf32() { unimplemented!("simdutf__utf16_length_from_utf32") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__utf16_length_from_utf8() { unimplemented!("simdutf__utf16_length_from_utf8") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__utf32_length_from_utf16le() { unimplemented!("simdutf__utf32_length_from_utf16le") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__utf32_length_from_utf8() { unimplemented!("simdutf__utf32_length_from_utf8") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__utf8_length_from_latin1() { unimplemented!("simdutf__utf8_length_from_latin1") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__utf8_length_from_utf16be() { unimplemented!("simdutf__utf8_length_from_utf16be") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__utf8_length_from_utf16le() { unimplemented!("simdutf__utf8_length_from_utf16le") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__utf8_length_from_utf32() { unimplemented!("simdutf__utf8_length_from_utf32") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__validate_ascii() { unimplemented!("simdutf__validate_ascii") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__validate_ascii_with_errors() { unimplemented!("simdutf__validate_ascii_with_errors") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__validate_utf16be() { unimplemented!("simdutf__validate_utf16be") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__validate_utf16be_with_errors() { unimplemented!("simdutf__validate_utf16be_with_errors") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__validate_utf16le() { unimplemented!("simdutf__validate_utf16le") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__validate_utf16le_with_errors() { unimplemented!("simdutf__validate_utf16le_with_errors") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__validate_utf32() { unimplemented!("simdutf__validate_utf32") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__validate_utf32_with_errors() { unimplemented!("simdutf__validate_utf32_with_errors") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__validate_utf8() { unimplemented!("simdutf__validate_utf8") }
#[unsafe(no_mangle)] pub extern "C" fn simdutf__validate_utf8_with_errors() { unimplemented!("simdutf__validate_utf8_with_errors") }
#[unsafe(no_mangle)] pub extern "C" fn std__shared_ptr__v8__BackingStore__CONVERT__std__unique_ptr() { unimplemented!("std__shared_ptr__v8__BackingStore__CONVERT__std__unique_ptr") }
#[unsafe(no_mangle)] pub extern "C" fn std__shared_ptr__v8__BackingStore__COPY() { unimplemented!("std__shared_ptr__v8__BackingStore__COPY") }
#[unsafe(no_mangle)] pub extern "C" fn std__shared_ptr__v8__BackingStore__get() { unimplemented!("std__shared_ptr__v8__BackingStore__get") }
#[unsafe(no_mangle)] pub extern "C" fn std__shared_ptr__v8__BackingStore__reset() { unimplemented!("std__shared_ptr__v8__BackingStore__reset") }
#[unsafe(no_mangle)] pub extern "C" fn std__shared_ptr__v8__BackingStore__use_count() { unimplemented!("std__shared_ptr__v8__BackingStore__use_count") }
#[unsafe(no_mangle)] pub extern "C" fn v8__AllowJavascriptExecutionScope__CONSTRUCT() { unimplemented!("v8__AllowJavascriptExecutionScope__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__AllowJavascriptExecutionScope__DESTRUCT() { unimplemented!("v8__AllowJavascriptExecutionScope__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Array__Length() { unimplemented!("v8__Array__Length") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Array__New() { unimplemented!("v8__Array__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Array__New_with_elements() { unimplemented!("v8__Array__New_with_elements") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBuffer__Allocator__NewRustAllocator() { unimplemented!("v8__ArrayBuffer__Allocator__NewRustAllocator") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBuffer__ByteLength() { unimplemented!("v8__ArrayBuffer__ByteLength") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBuffer__Data() { unimplemented!("v8__ArrayBuffer__Data") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBuffer__Detach() { unimplemented!("v8__ArrayBuffer__Detach") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBuffer__GetBackingStore() { unimplemented!("v8__ArrayBuffer__GetBackingStore") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBuffer__IsDetachable() { unimplemented!("v8__ArrayBuffer__IsDetachable") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBuffer__New__with_backing_store() { unimplemented!("v8__ArrayBuffer__New__with_backing_store") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBuffer__New__with_byte_length() { unimplemented!("v8__ArrayBuffer__New__with_byte_length") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBuffer__NewBackingStore__with_byte_length() { unimplemented!("v8__ArrayBuffer__NewBackingStore__with_byte_length") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBuffer__NewBackingStore__with_data() { unimplemented!("v8__ArrayBuffer__NewBackingStore__with_data") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBuffer__SetDetachKey() { unimplemented!("v8__ArrayBuffer__SetDetachKey") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBuffer__WasDetached() { unimplemented!("v8__ArrayBuffer__WasDetached") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBufferView__Buffer() { unimplemented!("v8__ArrayBufferView__Buffer") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBufferView__Buffer__Data() { unimplemented!("v8__ArrayBufferView__Buffer__Data") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBufferView__ByteLength() { unimplemented!("v8__ArrayBufferView__ByteLength") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBufferView__ByteOffset() { unimplemented!("v8__ArrayBufferView__ByteOffset") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBufferView__CopyContents() { unimplemented!("v8__ArrayBufferView__CopyContents") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBufferView__GetContents() { unimplemented!("v8__ArrayBufferView__GetContents") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ArrayBufferView__HasBuffer() { unimplemented!("v8__ArrayBufferView__HasBuffer") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BackingStore__ByteLength() { unimplemented!("v8__BackingStore__ByteLength") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BackingStore__Data() { unimplemented!("v8__BackingStore__Data") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BackingStore__DELETE() { unimplemented!("v8__BackingStore__DELETE") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BackingStore__IsResizableByUserJavaScript() { unimplemented!("v8__BackingStore__IsResizableByUserJavaScript") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BackingStore__IsShared() { unimplemented!("v8__BackingStore__IsShared") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BigInt__Int64Value() { unimplemented!("v8__BigInt__Int64Value") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BigInt__New() { unimplemented!("v8__BigInt__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BigInt__NewFromUnsigned() { unimplemented!("v8__BigInt__NewFromUnsigned") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BigInt__NewFromWords() { unimplemented!("v8__BigInt__NewFromWords") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BigInt__ToWordsArray() { unimplemented!("v8__BigInt__ToWordsArray") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BigInt__Uint64Value() { unimplemented!("v8__BigInt__Uint64Value") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BigInt__WordCount() { unimplemented!("v8__BigInt__WordCount") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BigInt64Array__New() { unimplemented!("v8__BigInt64Array__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__BigUint64Array__New() { unimplemented!("v8__BigUint64Array__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Boolean__New() { unimplemented!("v8__Boolean__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__CompiledWasmModule__DELETE() { unimplemented!("v8__CompiledWasmModule__DELETE") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__AllowCodeGenerationFromStrings() { unimplemented!("v8__Context__AllowCodeGenerationFromStrings") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__FromSnapshot() { unimplemented!("v8__Context__FromSnapshot") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__GetAlignedPointerFromEmbedderData() { unimplemented!("v8__Context__GetAlignedPointerFromEmbedderData") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__GetContinuationPreservedEmbedderData() { unimplemented!("v8__Context__GetContinuationPreservedEmbedderData") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__GetDataFromSnapshotOnce() { unimplemented!("v8__Context__GetDataFromSnapshotOnce") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__GetEmbedderData() { unimplemented!("v8__Context__GetEmbedderData") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__GetExtrasBindingObject() { unimplemented!("v8__Context__GetExtrasBindingObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__GetNumberOfEmbedderDataFields() { unimplemented!("v8__Context__GetNumberOfEmbedderDataFields") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__GetSecurityToken() { unimplemented!("v8__Context__GetSecurityToken") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__SetAlignedPointerInEmbedderData() { unimplemented!("v8__Context__SetAlignedPointerInEmbedderData") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__SetContinuationPreservedEmbedderData() { unimplemented!("v8__Context__SetContinuationPreservedEmbedderData") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__SetEmbedderData() { unimplemented!("v8__Context__SetEmbedderData") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__SetPromiseHooks() { unimplemented!("v8__Context__SetPromiseHooks") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context__SetSecurityToken() { unimplemented!("v8__Context__SetSecurityToken") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Context_IsCodeGenerationFromStringsAllowed() { unimplemented!("v8__Context_IsCodeGenerationFromStringsAllowed") }
#[unsafe(no_mangle)] pub extern "C" fn v8__CppHeap__Create() { unimplemented!("v8__CppHeap__Create") }
#[unsafe(no_mangle)] pub extern "C" fn v8__CppHeap__DELETE() { unimplemented!("v8__CppHeap__DELETE") }
#[unsafe(no_mangle)] pub extern "C" fn v8__CppHeap__Terminate() { unimplemented!("v8__CppHeap__Terminate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Data__EQ() { unimplemented!("v8__Data__EQ") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Data__IsFunctionTemplate() { unimplemented!("v8__Data__IsFunctionTemplate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Data__IsModule() { unimplemented!("v8__Data__IsModule") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Data__IsModuleRequest() { unimplemented!("v8__Data__IsModuleRequest") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Data__IsPrimitive() { unimplemented!("v8__Data__IsPrimitive") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Data__IsValue() { unimplemented!("v8__Data__IsValue") }
#[unsafe(no_mangle)] pub extern "C" fn v8__DataView__New() { unimplemented!("v8__DataView__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Date__New() { unimplemented!("v8__Date__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Date__ValueOf() { unimplemented!("v8__Date__ValueOf") }
#[unsafe(no_mangle)] pub extern "C" fn v8__DisallowJavascriptExecutionScope__CONSTRUCT() { unimplemented!("v8__DisallowJavascriptExecutionScope__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__DisallowJavascriptExecutionScope__DESTRUCT() { unimplemented!("v8__DisallowJavascriptExecutionScope__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__EscapeSlot__escape() { unimplemented!("v8__EscapeSlot__escape") }
#[unsafe(no_mangle)] pub extern "C" fn v8__EscapeSlot__reserve() { unimplemented!("v8__EscapeSlot__reserve") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Eternal__CONSTRUCT() { unimplemented!("v8__Eternal__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Eternal__DESTRUCT() { unimplemented!("v8__Eternal__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Eternal__Get() { unimplemented!("v8__Eternal__Get") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Eternal__Set() { unimplemented!("v8__Eternal__Set") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Exception__CreateMessage() { unimplemented!("v8__Exception__CreateMessage") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Exception__Error() { unimplemented!("v8__Exception__Error") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Exception__RangeError() { unimplemented!("v8__Exception__RangeError") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Exception__ReferenceError() { unimplemented!("v8__Exception__ReferenceError") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Exception__SyntaxError() { unimplemented!("v8__Exception__SyntaxError") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Exception__TypeError() { unimplemented!("v8__Exception__TypeError") }
#[unsafe(no_mangle)] pub extern "C" fn v8__External__New() { unimplemented!("v8__External__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__External__Value() { unimplemented!("v8__External__Value") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FixedArray__Get() { unimplemented!("v8__FixedArray__Get") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FixedArray__Length() { unimplemented!("v8__FixedArray__Length") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Float16Array__New() { unimplemented!("v8__Float16Array__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Float32Array__New() { unimplemented!("v8__Float32Array__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Float64Array__New() { unimplemented!("v8__Float64Array__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Function__Call() { unimplemented!("v8__Function__Call") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Function__CreateCodeCache() { unimplemented!("v8__Function__CreateCodeCache") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Function__New() { unimplemented!("v8__Function__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Function__NewInstance() { unimplemented!("v8__Function__NewInstance") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Function__SetName() { unimplemented!("v8__Function__SetName") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionCallbackInfo__Data() { unimplemented!("v8__FunctionCallbackInfo__Data") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionCallbackInfo__Get() { unimplemented!("v8__FunctionCallbackInfo__Get") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionCallbackInfo__GetIsolate() { unimplemented!("v8__FunctionCallbackInfo__GetIsolate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionCallbackInfo__GetParts() { unimplemented!("v8__FunctionCallbackInfo__GetParts") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionCallbackInfo__GetReturnValue() { unimplemented!("v8__FunctionCallbackInfo__GetReturnValue") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionCallbackInfo__Length() { unimplemented!("v8__FunctionCallbackInfo__Length") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionCallbackInfo__NewTarget() { unimplemented!("v8__FunctionCallbackInfo__NewTarget") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionCallbackInfo__This() { unimplemented!("v8__FunctionCallbackInfo__This") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionTemplate__GetFunction() { unimplemented!("v8__FunctionTemplate__GetFunction") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionTemplate__Inherit() { unimplemented!("v8__FunctionTemplate__Inherit") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionTemplate__InstanceTemplate() { unimplemented!("v8__FunctionTemplate__InstanceTemplate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionTemplate__New() { unimplemented!("v8__FunctionTemplate__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionTemplate__PrototypeTemplate() { unimplemented!("v8__FunctionTemplate__PrototypeTemplate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__FunctionTemplate__SetClassName() { unimplemented!("v8__FunctionTemplate__SetClassName") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Global__New() { unimplemented!("v8__Global__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Global__NewWeak() { unimplemented!("v8__Global__NewWeak") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Global__Reset() { unimplemented!("v8__Global__Reset") }
#[unsafe(no_mangle)] pub extern "C" fn v8__HeapProfiler__TakeHeapSnapshot() { unimplemented!("v8__HeapProfiler__TakeHeapSnapshot") }
#[unsafe(no_mangle)] pub extern "C" fn v8__HeapStatistics() { unimplemented!("v8__HeapStatistics") }
#[unsafe(no_mangle)] pub extern "C" fn v8__IdleTask__DELETE() { unimplemented!("v8__IdleTask__DELETE") }
#[unsafe(no_mangle)] pub extern "C" fn v8__IdleTask__Run() { unimplemented!("v8__IdleTask__Run") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Int16Array__New() { unimplemented!("v8__Int16Array__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Int32__Value() { unimplemented!("v8__Int32__Value") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Int32Array__New() { unimplemented!("v8__Int32Array__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Int8Array__New() { unimplemented!("v8__Int8Array__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Integer__New() { unimplemented!("v8__Integer__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Integer__NewFromUnsigned() { unimplemented!("v8__Integer__NewFromUnsigned") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Integer__Value() { unimplemented!("v8__Integer__Value") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__AddGCEpilogueCallback() { unimplemented!("v8__Isolate__AddGCEpilogueCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__AddGCPrologueCallback() { unimplemented!("v8__Isolate__AddGCPrologueCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__AddNearHeapLimitCallback() { unimplemented!("v8__Isolate__AddNearHeapLimitCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__AdjustAmountOfExternalAllocatedMemory() { unimplemented!("v8__Isolate__AdjustAmountOfExternalAllocatedMemory") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__CancelTerminateExecution() { unimplemented!("v8__Isolate__CancelTerminateExecution") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__DateTimeConfigurationChangeNotification() { unimplemented!("v8__Isolate__DateTimeConfigurationChangeNotification") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__EnqueueMicrotask() { unimplemented!("v8__Isolate__EnqueueMicrotask") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__GetCppHeap() { unimplemented!("v8__Isolate__GetCppHeap") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__GetEnteredOrMicrotaskContext() { unimplemented!("v8__Isolate__GetEnteredOrMicrotaskContext") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__GetHeapCodeAndMetadataStatistics() { unimplemented!("v8__Isolate__GetHeapCodeAndMetadataStatistics") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__GetHeapSpaceStatistics() { unimplemented!("v8__Isolate__GetHeapSpaceStatistics") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__GetHeapStatistics() { unimplemented!("v8__Isolate__GetHeapStatistics") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__HasPendingBackgroundTasks() { unimplemented!("v8__Isolate__HasPendingBackgroundTasks") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__IsExecutionTerminating() { unimplemented!("v8__Isolate__IsExecutionTerminating") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__LowMemoryNotification() { unimplemented!("v8__Isolate__LowMemoryNotification") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__NumberOfHeapSpaces() { unimplemented!("v8__Isolate__NumberOfHeapSpaces") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__PerformMicrotaskCheckpoint() { unimplemented!("v8__Isolate__PerformMicrotaskCheckpoint") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__RemoveNearHeapLimitCallback() { unimplemented!("v8__Isolate__RemoveNearHeapLimitCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__RequestInterrupt() { unimplemented!("v8__Isolate__RequestInterrupt") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__SetAllowWasmCodeGenerationCallback() { unimplemented!("v8__Isolate__SetAllowWasmCodeGenerationCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__SetCaptureStackTraceForUncaughtExceptions() { unimplemented!("v8__Isolate__SetCaptureStackTraceForUncaughtExceptions") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__SetHostCreateShadowRealmContextCallback() { unimplemented!("v8__Isolate__SetHostCreateShadowRealmContextCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__SetHostImportModuleDynamicallyCallback() { unimplemented!("v8__Isolate__SetHostImportModuleDynamicallyCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__SetHostImportModuleWithPhaseDynamicallyCallback() { unimplemented!("v8__Isolate__SetHostImportModuleWithPhaseDynamicallyCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__SetHostInitializeImportMetaObjectCallback() { unimplemented!("v8__Isolate__SetHostInitializeImportMetaObjectCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__SetIdle() { unimplemented!("v8__Isolate__SetIdle") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__SetMicrotasksPolicy() { unimplemented!("v8__Isolate__SetMicrotasksPolicy") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__SetPrepareStackTraceCallback() { unimplemented!("v8__Isolate__SetPrepareStackTraceCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__SetPromiseRejectCallback() { unimplemented!("v8__Isolate__SetPromiseRejectCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__SetWasmAsyncResolvePromiseCallback() { unimplemented!("v8__Isolate__SetWasmAsyncResolvePromiseCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__SetWasmStreamingCallback() { unimplemented!("v8__Isolate__SetWasmStreamingCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__TerminateExecution() { unimplemented!("v8__Isolate__TerminateExecution") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Isolate__ThrowException() { unimplemented!("v8__Isolate__ThrowException") }
#[unsafe(no_mangle)] pub extern "C" fn v8__JSON__Parse() { unimplemented!("v8__JSON__Parse") }
#[unsafe(no_mangle)] pub extern "C" fn v8__JSON__Stringify() { unimplemented!("v8__JSON__Stringify") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Location__GetColumnNumber() { unimplemented!("v8__Location__GetColumnNumber") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Location__GetLineNumber() { unimplemented!("v8__Location__GetLineNumber") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Map__As__Array() { unimplemented!("v8__Map__As__Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Map__Size() { unimplemented!("v8__Map__Size") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Message__Get() { unimplemented!("v8__Message__Get") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Message__GetLineNumber() { unimplemented!("v8__Message__GetLineNumber") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Message__GetScriptResourceName() { unimplemented!("v8__Message__GetScriptResourceName") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Message__GetSourceLine() { unimplemented!("v8__Message__GetSourceLine") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Message__GetStackTrace() { unimplemented!("v8__Message__GetStackTrace") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Message__GetStartColumn() { unimplemented!("v8__Message__GetStartColumn") }
#[unsafe(no_mangle)] pub extern "C" fn v8__MicrotaskQueue__DESTRUCT() { unimplemented!("v8__MicrotaskQueue__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__MicrotaskQueue__EnqueueMicrotask() { unimplemented!("v8__MicrotaskQueue__EnqueueMicrotask") }
#[unsafe(no_mangle)] pub extern "C" fn v8__MicrotaskQueue__GetMicrotasksScopeDepth() { unimplemented!("v8__MicrotaskQueue__GetMicrotasksScopeDepth") }
#[unsafe(no_mangle)] pub extern "C" fn v8__MicrotaskQueue__IsRunningMicrotasks() { unimplemented!("v8__MicrotaskQueue__IsRunningMicrotasks") }
#[unsafe(no_mangle)] pub extern "C" fn v8__MicrotaskQueue__New() { unimplemented!("v8__MicrotaskQueue__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__MicrotaskQueue__PerformCheckpoint() { unimplemented!("v8__MicrotaskQueue__PerformCheckpoint") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__CreateSyntheticModule() { unimplemented!("v8__Module__CreateSyntheticModule") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__Evaluate() { unimplemented!("v8__Module__Evaluate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__EvaluateForImportDefer() { unimplemented!("v8__Module__EvaluateForImportDefer") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__GetException() { unimplemented!("v8__Module__GetException") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__GetIdentityHash() { unimplemented!("v8__Module__GetIdentityHash") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__GetModuleNamespace() { unimplemented!("v8__Module__GetModuleNamespace") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__GetModuleNamespace2() { unimplemented!("v8__Module__GetModuleNamespace2") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__GetModuleRequests() { unimplemented!("v8__Module__GetModuleRequests") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__GetStalledTopLevelAwaitMessage() { unimplemented!("v8__Module__GetStalledTopLevelAwaitMessage") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__GetStatus() { unimplemented!("v8__Module__GetStatus") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__GetUnboundModuleScript() { unimplemented!("v8__Module__GetUnboundModuleScript") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__InstantiateModule() { unimplemented!("v8__Module__InstantiateModule") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__IsGraphAsync() { unimplemented!("v8__Module__IsGraphAsync") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__IsSyntheticModule() { unimplemented!("v8__Module__IsSyntheticModule") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__SetSyntheticModuleExport() { unimplemented!("v8__Module__SetSyntheticModuleExport") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Module__SourceOffsetToLocation() { unimplemented!("v8__Module__SourceOffsetToLocation") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ModuleRequest__GetImportAttributes() { unimplemented!("v8__ModuleRequest__GetImportAttributes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ModuleRequest__GetPhase() { unimplemented!("v8__ModuleRequest__GetPhase") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ModuleRequest__GetSourceOffset() { unimplemented!("v8__ModuleRequest__GetSourceOffset") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ModuleRequest__GetSpecifier() { unimplemented!("v8__ModuleRequest__GetSpecifier") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Name__GetIdentityHash() { unimplemented!("v8__Name__GetIdentityHash") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Null() { unimplemented!("v8__Null") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Number__New() { unimplemented!("v8__Number__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Number__Value() { unimplemented!("v8__Number__Value") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__CreateDataProperty() { unimplemented!("v8__Object__CreateDataProperty") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__DefineOwnProperty() { unimplemented!("v8__Object__DefineOwnProperty") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__DefineProperty() { unimplemented!("v8__Object__DefineProperty") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__Delete() { unimplemented!("v8__Object__Delete") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__DeleteIndex() { unimplemented!("v8__Object__DeleteIndex") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__DeletePrivate() { unimplemented!("v8__Object__DeletePrivate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__Get() { unimplemented!("v8__Object__Get") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__GetConstructorName() { unimplemented!("v8__Object__GetConstructorName") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__GetCreationContext() { unimplemented!("v8__Object__GetCreationContext") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__GetIdentityHash() { unimplemented!("v8__Object__GetIdentityHash") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__GetIndex() { unimplemented!("v8__Object__GetIndex") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__GetOwnPropertyDescriptor() { unimplemented!("v8__Object__GetOwnPropertyDescriptor") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__GetOwnPropertyNames() { unimplemented!("v8__Object__GetOwnPropertyNames") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__GetPrivate() { unimplemented!("v8__Object__GetPrivate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__GetPropertyAttributes() { unimplemented!("v8__Object__GetPropertyAttributes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__GetPropertyNames() { unimplemented!("v8__Object__GetPropertyNames") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__GetPrototype() { unimplemented!("v8__Object__GetPrototype") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__GetRealNamedProperty() { unimplemented!("v8__Object__GetRealNamedProperty") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__GetRealNamedPropertyAttributes() { unimplemented!("v8__Object__GetRealNamedPropertyAttributes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__Has() { unimplemented!("v8__Object__Has") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__HasIndex() { unimplemented!("v8__Object__HasIndex") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__HasOwnProperty() { unimplemented!("v8__Object__HasOwnProperty") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__HasPrivate() { unimplemented!("v8__Object__HasPrivate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__HasRealNamedProperty() { unimplemented!("v8__Object__HasRealNamedProperty") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__IsApiWrapper() { unimplemented!("v8__Object__IsApiWrapper") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__New() { unimplemented!("v8__Object__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__New__with_prototype_and_properties() { unimplemented!("v8__Object__New__with_prototype_and_properties") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__PreviewEntries() { unimplemented!("v8__Object__PreviewEntries") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__Set() { unimplemented!("v8__Object__Set") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__SetIndex() { unimplemented!("v8__Object__SetIndex") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__SetIntegrityLevel() { unimplemented!("v8__Object__SetIntegrityLevel") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__SetPrivate() { unimplemented!("v8__Object__SetPrivate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__SetPrototype() { unimplemented!("v8__Object__SetPrototype") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__Unwrap() { unimplemented!("v8__Object__Unwrap") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Object__Wrap() { unimplemented!("v8__Object__Wrap") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ObjectTemplate__New() { unimplemented!("v8__ObjectTemplate__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ObjectTemplate__NewInstance() { unimplemented!("v8__ObjectTemplate__NewInstance") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ObjectTemplate__SetAccessorProperty() { unimplemented!("v8__ObjectTemplate__SetAccessorProperty") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ObjectTemplate__SetIndexedPropertyHandler() { unimplemented!("v8__ObjectTemplate__SetIndexedPropertyHandler") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ObjectTemplate__SetInternalFieldCount() { unimplemented!("v8__ObjectTemplate__SetInternalFieldCount") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ObjectTemplate__SetNamedPropertyHandler() { unimplemented!("v8__ObjectTemplate__SetNamedPropertyHandler") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Platform__NewCustomPlatform() { unimplemented!("v8__Platform__NewCustomPlatform") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Platform__NewSingleThreadedDefaultPlatform() { unimplemented!("v8__Platform__NewSingleThreadedDefaultPlatform") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Platform__NewUnprotectedDefaultPlatform() { unimplemented!("v8__Platform__NewUnprotectedDefaultPlatform") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PrimitiveArray__Get() { unimplemented!("v8__PrimitiveArray__Get") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PrimitiveArray__Length() { unimplemented!("v8__PrimitiveArray__Length") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PrimitiveArray__New() { unimplemented!("v8__PrimitiveArray__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PrimitiveArray__Set() { unimplemented!("v8__PrimitiveArray__Set") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Private__ForApi() { unimplemented!("v8__Private__ForApi") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Private__New() { unimplemented!("v8__Private__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Promise__Catch() { unimplemented!("v8__Promise__Catch") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Promise__MarkAsHandled() { unimplemented!("v8__Promise__MarkAsHandled") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Promise__Resolver__GetPromise() { unimplemented!("v8__Promise__Resolver__GetPromise") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Promise__Resolver__New() { unimplemented!("v8__Promise__Resolver__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Promise__Resolver__Reject() { unimplemented!("v8__Promise__Resolver__Reject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Promise__Resolver__Resolve() { unimplemented!("v8__Promise__Resolver__Resolve") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Promise__Result() { unimplemented!("v8__Promise__Result") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Promise__State() { unimplemented!("v8__Promise__State") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Promise__Then2() { unimplemented!("v8__Promise__Then2") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PromiseRejectMessage__GetEvent() { unimplemented!("v8__PromiseRejectMessage__GetEvent") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PromiseRejectMessage__GetPromise() { unimplemented!("v8__PromiseRejectMessage__GetPromise") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PromiseRejectMessage__GetValue() { unimplemented!("v8__PromiseRejectMessage__GetValue") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyCallbackInfo__GetIsolate() { unimplemented!("v8__PropertyCallbackInfo__GetIsolate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyCallbackInfo__GetReturnValue() { unimplemented!("v8__PropertyCallbackInfo__GetReturnValue") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyCallbackInfo__Holder() { unimplemented!("v8__PropertyCallbackInfo__Holder") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyCallbackInfo__ShouldThrowOnError() { unimplemented!("v8__PropertyCallbackInfo__ShouldThrowOnError") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__configurable() { unimplemented!("v8__PropertyDescriptor__configurable") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__CONSTRUCT() { unimplemented!("v8__PropertyDescriptor__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__CONSTRUCT__Get_Set() { unimplemented!("v8__PropertyDescriptor__CONSTRUCT__Get_Set") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__CONSTRUCT__Value() { unimplemented!("v8__PropertyDescriptor__CONSTRUCT__Value") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__CONSTRUCT__Value_Writable() { unimplemented!("v8__PropertyDescriptor__CONSTRUCT__Value_Writable") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__DESTRUCT() { unimplemented!("v8__PropertyDescriptor__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__enumerable() { unimplemented!("v8__PropertyDescriptor__enumerable") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__get() { unimplemented!("v8__PropertyDescriptor__get") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__has_configurable() { unimplemented!("v8__PropertyDescriptor__has_configurable") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__has_enumerable() { unimplemented!("v8__PropertyDescriptor__has_enumerable") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__has_get() { unimplemented!("v8__PropertyDescriptor__has_get") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__has_set() { unimplemented!("v8__PropertyDescriptor__has_set") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__has_value() { unimplemented!("v8__PropertyDescriptor__has_value") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__has_writable() { unimplemented!("v8__PropertyDescriptor__has_writable") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__set() { unimplemented!("v8__PropertyDescriptor__set") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__set_configurable() { unimplemented!("v8__PropertyDescriptor__set_configurable") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__set_enumerable() { unimplemented!("v8__PropertyDescriptor__set_enumerable") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__value() { unimplemented!("v8__PropertyDescriptor__value") }
#[unsafe(no_mangle)] pub extern "C" fn v8__PropertyDescriptor__writable() { unimplemented!("v8__PropertyDescriptor__writable") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Proxy__GetHandler() { unimplemented!("v8__Proxy__GetHandler") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Proxy__GetTarget() { unimplemented!("v8__Proxy__GetTarget") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__code_range_size_in_bytes() { unimplemented!("v8__ResourceConstraints__code_range_size_in_bytes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__ConfigureDefaults() { unimplemented!("v8__ResourceConstraints__ConfigureDefaults") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__ConfigureDefaultsFromHeapSize() { unimplemented!("v8__ResourceConstraints__ConfigureDefaultsFromHeapSize") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__initial_old_generation_size_in_bytes() { unimplemented!("v8__ResourceConstraints__initial_old_generation_size_in_bytes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__initial_young_generation_size_in_bytes() { unimplemented!("v8__ResourceConstraints__initial_young_generation_size_in_bytes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__max_old_generation_size_in_bytes() { unimplemented!("v8__ResourceConstraints__max_old_generation_size_in_bytes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__max_young_generation_size_in_bytes() { unimplemented!("v8__ResourceConstraints__max_young_generation_size_in_bytes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__set_code_range_size_in_bytes() { unimplemented!("v8__ResourceConstraints__set_code_range_size_in_bytes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__set_initial_old_generation_size_in_bytes() { unimplemented!("v8__ResourceConstraints__set_initial_old_generation_size_in_bytes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__set_initial_young_generation_size_in_bytes() { unimplemented!("v8__ResourceConstraints__set_initial_young_generation_size_in_bytes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__set_max_old_generation_size_in_bytes() { unimplemented!("v8__ResourceConstraints__set_max_old_generation_size_in_bytes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__set_max_young_generation_size_in_bytes() { unimplemented!("v8__ResourceConstraints__set_max_young_generation_size_in_bytes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__set_stack_limit() { unimplemented!("v8__ResourceConstraints__set_stack_limit") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ResourceConstraints__stack_limit() { unimplemented!("v8__ResourceConstraints__stack_limit") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ReturnValue__Value__Set() { unimplemented!("v8__ReturnValue__Value__Set") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ReturnValue__Value__Set__Bool() { unimplemented!("v8__ReturnValue__Value__Set__Bool") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ReturnValue__Value__Set__Double() { unimplemented!("v8__ReturnValue__Value__Set__Double") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ReturnValue__Value__Set__Int32() { unimplemented!("v8__ReturnValue__Value__Set__Int32") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ReturnValue__Value__Set__Uint32() { unimplemented!("v8__ReturnValue__Value__Set__Uint32") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ReturnValue__Value__SetNull() { unimplemented!("v8__ReturnValue__Value__SetNull") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Script__GetUnboundScript() { unimplemented!("v8__Script__GetUnboundScript") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ScriptCompiler__CachedData__DELETE() { unimplemented!("v8__ScriptCompiler__CachedData__DELETE") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ScriptCompiler__CachedData__NEW() { unimplemented!("v8__ScriptCompiler__CachedData__NEW") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ScriptCompiler__CachedDataVersionTag() { unimplemented!("v8__ScriptCompiler__CachedDataVersionTag") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ScriptCompiler__Compile() { unimplemented!("v8__ScriptCompiler__Compile") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ScriptCompiler__CompileFunction() { unimplemented!("v8__ScriptCompiler__CompileFunction") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ScriptCompiler__CompileModule() { unimplemented!("v8__ScriptCompiler__CompileModule") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ScriptCompiler__CompileUnboundScript() { unimplemented!("v8__ScriptCompiler__CompileUnboundScript") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ScriptCompiler__Source__CONSTRUCT() { unimplemented!("v8__ScriptCompiler__Source__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ScriptCompiler__Source__DESTRUCT() { unimplemented!("v8__ScriptCompiler__Source__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ScriptCompiler__Source__GetCachedData() { unimplemented!("v8__ScriptCompiler__Source__GetCachedData") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ScriptOrigin__CONSTRUCT() { unimplemented!("v8__ScriptOrigin__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Set__Add() { unimplemented!("v8__Set__Add") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Set__As__Array() { unimplemented!("v8__Set__As__Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Set__New() { unimplemented!("v8__Set__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Set__Size() { unimplemented!("v8__Set__Size") }
#[unsafe(no_mangle)] pub extern "C" fn v8__SharedArrayBuffer__ByteLength() { unimplemented!("v8__SharedArrayBuffer__ByteLength") }
#[unsafe(no_mangle)] pub extern "C" fn v8__SharedArrayBuffer__GetBackingStore() { unimplemented!("v8__SharedArrayBuffer__GetBackingStore") }
#[unsafe(no_mangle)] pub extern "C" fn v8__SharedArrayBuffer__New__with_backing_store() { unimplemented!("v8__SharedArrayBuffer__New__with_backing_store") }
#[unsafe(no_mangle)] pub extern "C" fn v8__SnapshotCreator__AddContext() { unimplemented!("v8__SnapshotCreator__AddContext") }
#[unsafe(no_mangle)] pub extern "C" fn v8__SnapshotCreator__AddData_to_context() { unimplemented!("v8__SnapshotCreator__AddData_to_context") }
#[unsafe(no_mangle)] pub extern "C" fn v8__SnapshotCreator__CONSTRUCT() { unimplemented!("v8__SnapshotCreator__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__SnapshotCreator__CreateBlob() { unimplemented!("v8__SnapshotCreator__CreateBlob") }
#[unsafe(no_mangle)] pub extern "C" fn v8__SnapshotCreator__DESTRUCT() { unimplemented!("v8__SnapshotCreator__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__SnapshotCreator__GetIsolate() { unimplemented!("v8__SnapshotCreator__GetIsolate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__SnapshotCreator__SetDefaultContext() { unimplemented!("v8__SnapshotCreator__SetDefaultContext") }
#[unsafe(no_mangle)] pub extern "C" fn v8__StackFrame__GetColumn() { unimplemented!("v8__StackFrame__GetColumn") }
#[unsafe(no_mangle)] pub extern "C" fn v8__StackFrame__GetFunctionName() { unimplemented!("v8__StackFrame__GetFunctionName") }
#[unsafe(no_mangle)] pub extern "C" fn v8__StackFrame__GetLineNumber() { unimplemented!("v8__StackFrame__GetLineNumber") }
#[unsafe(no_mangle)] pub extern "C" fn v8__StackFrame__GetScriptName() { unimplemented!("v8__StackFrame__GetScriptName") }
#[unsafe(no_mangle)] pub extern "C" fn v8__StackFrame__IsEval() { unimplemented!("v8__StackFrame__IsEval") }
#[unsafe(no_mangle)] pub extern "C" fn v8__StackFrame__IsUserJavaScript() { unimplemented!("v8__StackFrame__IsUserJavaScript") }
#[unsafe(no_mangle)] pub extern "C" fn v8__StackTrace__CurrentStackTrace() { unimplemented!("v8__StackTrace__CurrentStackTrace") }
#[unsafe(no_mangle)] pub extern "C" fn v8__StackTrace__GetFrame() { unimplemented!("v8__StackTrace__GetFrame") }
#[unsafe(no_mangle)] pub extern "C" fn v8__StackTrace__GetFrameCount() { unimplemented!("v8__StackTrace__GetFrameCount") }
#[unsafe(no_mangle)] pub extern "C" fn v8__StartupData__CanBeRehashed() { unimplemented!("v8__StartupData__CanBeRehashed") }
#[unsafe(no_mangle)] pub extern "C" fn v8__StartupData__data__DELETE() { unimplemented!("v8__StartupData__data__DELETE") }
#[unsafe(no_mangle)] pub extern "C" fn v8__StartupData__IsValid() { unimplemented!("v8__StartupData__IsValid") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__ContainsOnlyOneByte() { unimplemented!("v8__String__ContainsOnlyOneByte") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__Empty() { unimplemented!("v8__String__Empty") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__GetExternalStringResourceBase() { unimplemented!("v8__String__GetExternalStringResourceBase") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__IsOneByte() { unimplemented!("v8__String__IsOneByte") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__NewExternalOneByte() { unimplemented!("v8__String__NewExternalOneByte") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__NewExternalOneByteConst() { unimplemented!("v8__String__NewExternalOneByteConst") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__NewExternalOneByteStatic() { unimplemented!("v8__String__NewExternalOneByteStatic") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__NewExternalTwoByte() { unimplemented!("v8__String__NewExternalTwoByte") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__NewFromTwoByte() { unimplemented!("v8__String__NewFromTwoByte") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__Utf8Length() { unimplemented!("v8__String__Utf8Length") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__ValueView_SIZE() { unimplemented!("v8__String__ValueView_SIZE") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__Write_v2() { unimplemented!("v8__String__Write_v2") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__WriteOneByte_v2() { unimplemented!("v8__String__WriteOneByte_v2") }
#[unsafe(no_mangle)] pub extern "C" fn v8__String__WriteUtf8_v2() { unimplemented!("v8__String__WriteUtf8_v2") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__Description() { unimplemented!("v8__Symbol__Description") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__For() { unimplemented!("v8__Symbol__For") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__GetAsyncIterator() { unimplemented!("v8__Symbol__GetAsyncIterator") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__GetHasInstance() { unimplemented!("v8__Symbol__GetHasInstance") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__GetIsConcatSpreadable() { unimplemented!("v8__Symbol__GetIsConcatSpreadable") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__GetIterator() { unimplemented!("v8__Symbol__GetIterator") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__GetMatch() { unimplemented!("v8__Symbol__GetMatch") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__GetReplace() { unimplemented!("v8__Symbol__GetReplace") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__GetSearch() { unimplemented!("v8__Symbol__GetSearch") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__GetSplit() { unimplemented!("v8__Symbol__GetSplit") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__GetToPrimitive() { unimplemented!("v8__Symbol__GetToPrimitive") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__GetToStringTag() { unimplemented!("v8__Symbol__GetToStringTag") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__GetUnscopables() { unimplemented!("v8__Symbol__GetUnscopables") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Symbol__New() { unimplemented!("v8__Symbol__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Task__DELETE() { unimplemented!("v8__Task__DELETE") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Task__Run() { unimplemented!("v8__Task__Run") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Template__Set() { unimplemented!("v8__Template__Set") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TracedReference__CONSTRUCT() { unimplemented!("v8__TracedReference__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TracedReference__DESTRUCT() { unimplemented!("v8__TracedReference__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TracedReference__Get() { unimplemented!("v8__TracedReference__Get") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TracedReference__Reset() { unimplemented!("v8__TracedReference__Reset") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TryCatch__CONSTRUCT() { unimplemented!("v8__TryCatch__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TryCatch__DESTRUCT() { unimplemented!("v8__TryCatch__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TryCatch__Exception() { unimplemented!("v8__TryCatch__Exception") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TryCatch__HasCaught() { unimplemented!("v8__TryCatch__HasCaught") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TryCatch__HasTerminated() { unimplemented!("v8__TryCatch__HasTerminated") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TryCatch__Message() { unimplemented!("v8__TryCatch__Message") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TryCatch__Reset() { unimplemented!("v8__TryCatch__Reset") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TryCatch__ReThrow() { unimplemented!("v8__TryCatch__ReThrow") }
#[unsafe(no_mangle)] pub extern "C" fn v8__TypedArray__Length() { unimplemented!("v8__TypedArray__Length") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Uint16Array__New() { unimplemented!("v8__Uint16Array__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Uint32__Value() { unimplemented!("v8__Uint32__Value") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Uint32Array__New() { unimplemented!("v8__Uint32Array__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Uint8Array__New() { unimplemented!("v8__Uint8Array__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Uint8ClampedArray__New() { unimplemented!("v8__Uint8ClampedArray__New") }
#[unsafe(no_mangle)] pub extern "C" fn v8__UnboundModuleScript__CreateCodeCache() { unimplemented!("v8__UnboundModuleScript__CreateCodeCache") }
#[unsafe(no_mangle)] pub extern "C" fn v8__UnboundModuleScript__GetSourceMappingURL() { unimplemented!("v8__UnboundModuleScript__GetSourceMappingURL") }
#[unsafe(no_mangle)] pub extern "C" fn v8__UnboundModuleScript__GetSourceURL() { unimplemented!("v8__UnboundModuleScript__GetSourceURL") }
#[unsafe(no_mangle)] pub extern "C" fn v8__UnboundScript__BindToCurrentContext() { unimplemented!("v8__UnboundScript__BindToCurrentContext") }
#[unsafe(no_mangle)] pub extern "C" fn v8__UnboundScript__CreateCodeCache() { unimplemented!("v8__UnboundScript__CreateCodeCache") }
#[unsafe(no_mangle)] pub extern "C" fn v8__UnboundScript__GetSourceMappingURL() { unimplemented!("v8__UnboundScript__GetSourceMappingURL") }
#[unsafe(no_mangle)] pub extern "C" fn v8__V8__IsSandboxEnabled() { unimplemented!("v8__V8__IsSandboxEnabled") }
#[unsafe(no_mangle)] pub extern "C" fn v8__V8__SetFatalErrorHandler() { unimplemented!("v8__V8__SetFatalErrorHandler") }
#[unsafe(no_mangle)] pub extern "C" fn v8__V8__SetFlagsFromCommandLine() { unimplemented!("v8__V8__SetFlagsFromCommandLine") }
#[unsafe(no_mangle)] pub extern "C" fn v8__V8__SetFlagsFromString() { unimplemented!("v8__V8__SetFlagsFromString") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__BooleanValue() { unimplemented!("v8__Value__BooleanValue") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__InstanceOf() { unimplemented!("v8__Value__InstanceOf") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__Int32Value() { unimplemented!("v8__Value__Int32Value") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IntegerValue() { unimplemented!("v8__Value__IntegerValue") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsArgumentsObject() { unimplemented!("v8__Value__IsArgumentsObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsArray() { unimplemented!("v8__Value__IsArray") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsArrayBuffer() { unimplemented!("v8__Value__IsArrayBuffer") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsArrayBufferView() { unimplemented!("v8__Value__IsArrayBufferView") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsAsyncFunction() { unimplemented!("v8__Value__IsAsyncFunction") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsBigInt() { unimplemented!("v8__Value__IsBigInt") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsBigInt64Array() { unimplemented!("v8__Value__IsBigInt64Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsBigIntObject() { unimplemented!("v8__Value__IsBigIntObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsBigUint64Array() { unimplemented!("v8__Value__IsBigUint64Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsBoolean() { unimplemented!("v8__Value__IsBoolean") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsBooleanObject() { unimplemented!("v8__Value__IsBooleanObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsDataView() { unimplemented!("v8__Value__IsDataView") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsDate() { unimplemented!("v8__Value__IsDate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsExternal() { unimplemented!("v8__Value__IsExternal") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsFalse() { unimplemented!("v8__Value__IsFalse") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsFloat16Array() { unimplemented!("v8__Value__IsFloat16Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsFloat32Array() { unimplemented!("v8__Value__IsFloat32Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsFloat64Array() { unimplemented!("v8__Value__IsFloat64Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsFunction() { unimplemented!("v8__Value__IsFunction") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsGeneratorFunction() { unimplemented!("v8__Value__IsGeneratorFunction") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsInt16Array() { unimplemented!("v8__Value__IsInt16Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsInt32() { unimplemented!("v8__Value__IsInt32") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsInt32Array() { unimplemented!("v8__Value__IsInt32Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsInt8Array() { unimplemented!("v8__Value__IsInt8Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsMap() { unimplemented!("v8__Value__IsMap") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsMapIterator() { unimplemented!("v8__Value__IsMapIterator") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsModuleNamespaceObject() { unimplemented!("v8__Value__IsModuleNamespaceObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsName() { unimplemented!("v8__Value__IsName") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsNativeError() { unimplemented!("v8__Value__IsNativeError") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsNull() { unimplemented!("v8__Value__IsNull") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsNullOrUndefined() { unimplemented!("v8__Value__IsNullOrUndefined") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsNumber() { unimplemented!("v8__Value__IsNumber") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsNumberObject() { unimplemented!("v8__Value__IsNumberObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsObject() { unimplemented!("v8__Value__IsObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsPromise() { unimplemented!("v8__Value__IsPromise") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsProxy() { unimplemented!("v8__Value__IsProxy") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsRegExp() { unimplemented!("v8__Value__IsRegExp") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsSet() { unimplemented!("v8__Value__IsSet") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsSetGeneratorObject() { unimplemented!("v8__Value__IsSetGeneratorObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsSetIterator() { unimplemented!("v8__Value__IsSetIterator") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsSharedArrayBuffer() { unimplemented!("v8__Value__IsSharedArrayBuffer") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsString() { unimplemented!("v8__Value__IsString") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsStringObject() { unimplemented!("v8__Value__IsStringObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsSymbol() { unimplemented!("v8__Value__IsSymbol") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsSymbolObject() { unimplemented!("v8__Value__IsSymbolObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsTrue() { unimplemented!("v8__Value__IsTrue") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsTypedArray() { unimplemented!("v8__Value__IsTypedArray") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsUint16Array() { unimplemented!("v8__Value__IsUint16Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsUint32() { unimplemented!("v8__Value__IsUint32") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsUint32Array() { unimplemented!("v8__Value__IsUint32Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsUint8Array() { unimplemented!("v8__Value__IsUint8Array") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsUint8ClampedArray() { unimplemented!("v8__Value__IsUint8ClampedArray") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsUndefined() { unimplemented!("v8__Value__IsUndefined") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsWasmMemoryObject() { unimplemented!("v8__Value__IsWasmMemoryObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsWasmModuleObject() { unimplemented!("v8__Value__IsWasmModuleObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsWeakMap() { unimplemented!("v8__Value__IsWeakMap") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__IsWeakSet() { unimplemented!("v8__Value__IsWeakSet") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__NumberValue() { unimplemented!("v8__Value__NumberValue") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__SameValue() { unimplemented!("v8__Value__SameValue") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__StrictEquals() { unimplemented!("v8__Value__StrictEquals") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__ToBigInt() { unimplemented!("v8__Value__ToBigInt") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__ToBoolean() { unimplemented!("v8__Value__ToBoolean") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__ToInteger() { unimplemented!("v8__Value__ToInteger") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__ToNumber() { unimplemented!("v8__Value__ToNumber") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__ToObject() { unimplemented!("v8__Value__ToObject") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__TypeOf() { unimplemented!("v8__Value__TypeOf") }
#[unsafe(no_mangle)] pub extern "C" fn v8__Value__Uint32Value() { unimplemented!("v8__Value__Uint32Value") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__CONSTRUCT() { unimplemented!("v8__ValueDeserializer__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__Delegate__CONSTRUCT() { unimplemented!("v8__ValueDeserializer__Delegate__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__DESTRUCT() { unimplemented!("v8__ValueDeserializer__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__GetWireFormatVersion() { unimplemented!("v8__ValueDeserializer__GetWireFormatVersion") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__ReadDouble() { unimplemented!("v8__ValueDeserializer__ReadDouble") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__ReadHeader() { unimplemented!("v8__ValueDeserializer__ReadHeader") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__ReadRawBytes() { unimplemented!("v8__ValueDeserializer__ReadRawBytes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__ReadUint32() { unimplemented!("v8__ValueDeserializer__ReadUint32") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__ReadUint64() { unimplemented!("v8__ValueDeserializer__ReadUint64") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__ReadValue() { unimplemented!("v8__ValueDeserializer__ReadValue") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__SetSupportsLegacyWireFormat() { unimplemented!("v8__ValueDeserializer__SetSupportsLegacyWireFormat") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__TransferArrayBuffer() { unimplemented!("v8__ValueDeserializer__TransferArrayBuffer") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueDeserializer__TransferSharedArrayBuffer() { unimplemented!("v8__ValueDeserializer__TransferSharedArrayBuffer") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueSerializer__CONSTRUCT() { unimplemented!("v8__ValueSerializer__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueSerializer__Delegate__CONSTRUCT() { unimplemented!("v8__ValueSerializer__Delegate__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueSerializer__DESTRUCT() { unimplemented!("v8__ValueSerializer__DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueSerializer__Release() { unimplemented!("v8__ValueSerializer__Release") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueSerializer__SetTreatArrayBufferViewsAsHostObjects() { unimplemented!("v8__ValueSerializer__SetTreatArrayBufferViewsAsHostObjects") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueSerializer__TransferArrayBuffer() { unimplemented!("v8__ValueSerializer__TransferArrayBuffer") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueSerializer__WriteDouble() { unimplemented!("v8__ValueSerializer__WriteDouble") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueSerializer__WriteHeader() { unimplemented!("v8__ValueSerializer__WriteHeader") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueSerializer__WriteRawBytes() { unimplemented!("v8__ValueSerializer__WriteRawBytes") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueSerializer__WriteUint32() { unimplemented!("v8__ValueSerializer__WriteUint32") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueSerializer__WriteUint64() { unimplemented!("v8__ValueSerializer__WriteUint64") }
#[unsafe(no_mangle)] pub extern "C" fn v8__ValueSerializer__WriteValue() { unimplemented!("v8__ValueSerializer__WriteValue") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WasmModuleCompilation__DELETE() { unimplemented!("v8__WasmModuleCompilation__DELETE") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WasmModuleCompilation__NEW() { unimplemented!("v8__WasmModuleCompilation__NEW") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WasmModuleObject__Compile() { unimplemented!("v8__WasmModuleObject__Compile") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WasmModuleObject__FromCompiledModule() { unimplemented!("v8__WasmModuleObject__FromCompiledModule") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WasmModuleObject__GetCompiledModule() { unimplemented!("v8__WasmModuleObject__GetCompiledModule") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WasmStreaming__Abort() { unimplemented!("v8__WasmStreaming__Abort") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WasmStreaming__Finish() { unimplemented!("v8__WasmStreaming__Finish") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WasmStreaming__OnBytesReceived() { unimplemented!("v8__WasmStreaming__OnBytesReceived") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WasmStreaming__SetUrl() { unimplemented!("v8__WasmStreaming__SetUrl") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WasmStreaming__shared_ptr_DESTRUCT() { unimplemented!("v8__WasmStreaming__shared_ptr_DESTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WasmStreaming__Unpack() { unimplemented!("v8__WasmStreaming__Unpack") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WeakCallbackInfo__GetIsolate() { unimplemented!("v8__WeakCallbackInfo__GetIsolate") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WeakCallbackInfo__GetParameter() { unimplemented!("v8__WeakCallbackInfo__GetParameter") }
#[unsafe(no_mangle)] pub extern "C" fn v8__WeakCallbackInfo__SetSecondPassCallback() { unimplemented!("v8__WeakCallbackInfo__SetSecondPassCallback") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__StringBuffer__create() { unimplemented!("v8_inspector__StringBuffer__create") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__StringBuffer__DELETE() { unimplemented!("v8_inspector__StringBuffer__DELETE") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__StringBuffer__string() { unimplemented!("v8_inspector__StringBuffer__string") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__allAsyncTasksCanceled() { unimplemented!("v8_inspector__V8Inspector__allAsyncTasksCanceled") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__asyncTaskCanceled() { unimplemented!("v8_inspector__V8Inspector__asyncTaskCanceled") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__asyncTaskFinished() { unimplemented!("v8_inspector__V8Inspector__asyncTaskFinished") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__asyncTaskScheduled() { unimplemented!("v8_inspector__V8Inspector__asyncTaskScheduled") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__asyncTaskStarted() { unimplemented!("v8_inspector__V8Inspector__asyncTaskStarted") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__Channel__BASE__CONSTRUCT() { unimplemented!("v8_inspector__V8Inspector__Channel__BASE__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__Channel__flushProtocolNotifications() { unimplemented!("v8_inspector__V8Inspector__Channel__flushProtocolNotifications") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__Channel__sendNotification() { unimplemented!("v8_inspector__V8Inspector__Channel__sendNotification") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__Channel__sendResponse() { unimplemented!("v8_inspector__V8Inspector__Channel__sendResponse") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__connect() { unimplemented!("v8_inspector__V8Inspector__connect") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__contextCreated() { unimplemented!("v8_inspector__V8Inspector__contextCreated") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__contextDestroyed() { unimplemented!("v8_inspector__V8Inspector__contextDestroyed") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__create() { unimplemented!("v8_inspector__V8Inspector__create") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__createStackTrace() { unimplemented!("v8_inspector__V8Inspector__createStackTrace") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__DELETE() { unimplemented!("v8_inspector__V8Inspector__DELETE") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__exceptionThrown() { unimplemented!("v8_inspector__V8Inspector__exceptionThrown") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__idleFinished() { unimplemented!("v8_inspector__V8Inspector__idleFinished") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8Inspector__idleStarted() { unimplemented!("v8_inspector__V8Inspector__idleStarted") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8InspectorClient__BASE__CONSTRUCT() { unimplemented!("v8_inspector__V8InspectorClient__BASE__CONSTRUCT") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8InspectorClient__consoleAPIMessage() { unimplemented!("v8_inspector__V8InspectorClient__consoleAPIMessage") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8InspectorClient__generateUniqueId() { unimplemented!("v8_inspector__V8InspectorClient__generateUniqueId") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8InspectorClient__quitMessageLoopOnPause() { unimplemented!("v8_inspector__V8InspectorClient__quitMessageLoopOnPause") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8InspectorClient__runIfWaitingForDebugger() { unimplemented!("v8_inspector__V8InspectorClient__runIfWaitingForDebugger") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8InspectorClient__runMessageLoopOnPause() { unimplemented!("v8_inspector__V8InspectorClient__runMessageLoopOnPause") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8InspectorSession__cancelPauseOnNextStatement() { unimplemented!("v8_inspector__V8InspectorSession__cancelPauseOnNextStatement") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8InspectorSession__canDispatchMethod() { unimplemented!("v8_inspector__V8InspectorSession__canDispatchMethod") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8InspectorSession__DELETE() { unimplemented!("v8_inspector__V8InspectorSession__DELETE") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8InspectorSession__dispatchProtocolMessage() { unimplemented!("v8_inspector__V8InspectorSession__dispatchProtocolMessage") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8InspectorSession__schedulePauseOnNextStatement() { unimplemented!("v8_inspector__V8InspectorSession__schedulePauseOnNextStatement") }
#[unsafe(no_mangle)] pub extern "C" fn v8_inspector__V8StackTrace__DELETE() { unimplemented!("v8_inspector__V8StackTrace__DELETE") }
