//! Hermes engine backend for the v8 C-ABI compat layer (spike).
//!
//! Cycle 0/1 scaffold: this module makes `cargo build --features hermes`
//! compile and link with a pure-Rust stub backend and zero Hermes dependency.
//! Every `v8__*`/`v8_inspector__*` symbol the vendored rusty_v8 surface
//! declares is defined in `shims` as an `unimplemented!()` no-arg stub
//! (auto-generated by tools/gen_hermes_shims.sh); `cppgc__*` stubs live in
//! `misc`. Nothing here runs real JavaScript yet. See
//! docs/hermes-spike/NOTES.md ("Cycle 0 - integration surface") for the plan:
//! a real backend is a clone of src/quickjs/'s arena-handle shape (Hermes JSI
//! values are NaN-boxed structs like QuickJS's `JSValue`, not JSC-style
//! pointer punning), built against Hermes's C++ JSI through an extern "C"
//! bridge.

// The real backend core (hello-world path: isolate/context/handle-scope/
// string/script) is authored against the C++/JSI bridge and therefore only
// exists when `link_hermes` links a real libhermes. Without it, the pure-Rust
// stub build keeps the auto-generated stubs for these symbols in `shims`.
#[cfg(feature = "link_hermes")]
mod core;
// E1: async-generator source-to-source lowering (oxc-based). Available whenever
// the Hermes backend is built (`engine_hermes` pulls in the oxc dependency),
// independent of whether a real libhermes is linked, so its unit tests run in
// the pure-Rust stub build too. Wired into the compile boundary in `core`/
// `modules` (which only exist under `link_hermes`).
#[cfg(feature = "engine_hermes")]
mod lower;
#[cfg(feature = "link_hermes")]
mod modules;
mod misc;
// E5: v8::ValueSerializer/Deserializer (structuredClone wire format) over JSI
// values. Needs the live Hermes runtime (the C++ walk helpers), so link_hermes.
#[cfg(feature = "link_hermes")]
mod serializer;
mod shims;

// Pure-Rust simdutf__* C-ABI surface (UTF validation/conversion/base64) the
// vendored rusty_v8 `simdutf` binding references on Deno's hot path. It is
// engine-independent, so the Hermes backend reuses the real implementation
// authored for the quickjs backend rather than re-stubbing it. Gated to match
// the rusty_v8 simdutf binding (lib.rs, feature = "simdutf"), which is what
// references these symbols; without it deno_core fails to link.
#[cfg(feature = "simdutf")]
#[path = "../quickjs/simdutf.rs"]
mod simdutf;

// Feasibility proof (C2): with `--features link_hermes`, build.rs compiles
// src/hermes/hermes_eval_shim.cpp against a real libhermes and links it. The
// extern "C" bridge below reaches jsi::Runtime::evaluateJavaScript through
// that shim. This is the go/no-go for the whole engine_hermes idea: Hermes is
// C++-only JSI, so proving a Rust -> extern "C" C++ -> real Hermes -> value
// round-trip de-risks authoring the full v8__* surface the same way. Gated on
// `link_hermes` so the default `--features hermes` stub build stays dependency
// free. See docs/hermes-spike/experiments/C2-hermes-ffi.md.
#[cfg(feature = "link_hermes")]
mod smoke {
  unsafe extern "C" {
    fn v8x_hermes_smoke_eval(src: *const std::os::raw::c_char) -> i32;
  }

  /// Evaluate `src` on a fresh HermesRuntime and return the numeric result as
  /// an `i32`. Negative sentinels (`<= -1000`) signal a non-number result, a
  /// JS error, or a C++ error caught at the boundary. `src` must be valid
  /// UTF-8 with no interior NUL.
  pub fn smoke_eval(src: &str) -> i32 {
    let c = std::ffi::CString::new(src).expect("src has interior NUL");
    // SAFETY: the shim catches every C++ exception before returning, so no
    // unwinding crosses this boundary; `c` outlives the call.
    unsafe { v8x_hermes_smoke_eval(c.as_ptr()) }
  }
}

#[cfg(feature = "link_hermes")]
pub use smoke::smoke_eval;

// C5: parse-free AOT execution. HermesRuntime::evaluateJavaScript already
// sniffs its input buffer for the 8-byte HBC magic (isHermesBytecode) and
// skips parsing/compiling entirely when it matches; otherwise the buffer is
// treated as UTF-8 JS source and parsed+compiled as usual. This module is a
// minimal, standalone harness (one HermesRuntime per call, like `smoke`
// above) that proves the SAME entry point runs plain source or a
// hermesc-compiled `.hbc` buffer, and lets a caller measure the parse+compile
// cost recovered by feeding precompiled HBC instead of source. See
// docs/hermes-spike/experiments/C5-hermes-hbc-aot.md.
#[cfg(feature = "link_hermes")]
pub mod aot {
  use std::ffi::CString;
  use std::os::raw::{c_char, c_int, c_void};

  unsafe extern "C" {
    fn v8x_hermes_runtime_new() -> *mut c_void;
    fn v8x_hermes_runtime_free(rtw: *mut c_void);
    fn v8x_hermes_is_hbc(data: *const u8, len: usize) -> c_int;
    fn v8x_hermes_eval_buffer(
      rtw: *mut c_void,
      data: *const u8,
      len: usize,
      source_url: *const c_char,
      ok: *mut c_int,
    ) -> i64;
    fn v8x_hermes_value_to_utf8(
      rtw: *mut c_void,
      slot: i64,
      out: *mut c_char,
      cap: usize,
    ) -> usize;
  }

  /// A single-runtime handle for the AOT proof/bench. Frees the underlying
  /// HermesRuntime on drop.
  pub struct Rt(*mut c_void);

  impl Rt {
    /// Create a fresh HermesRuntime. Panics if construction throws in the
    /// shim (mirrors the `assert!` in `core.rs`'s `v8__Isolate__New`).
    pub fn new() -> Self {
      let rtw = unsafe { v8x_hermes_runtime_new() };
      assert!(!rtw.is_null(), "v8x_hermes_runtime_new failed");
      Rt(rtw)
    }

    /// Evaluate a raw byte buffer (JS source OR Hermes bytecode; Hermes
    /// sniffs which). Returns the result coerced to a Rust `String` via
    /// `Value::toString`, or `None` on any error (bad input on either path,
    /// or a thrown JS error).
    pub fn eval_buffer(&self, buf: &[u8], source_url: &str) -> Option<String> {
      let url = CString::new(source_url).unwrap();
      let mut ok: c_int = 0;
      let slot = unsafe {
        v8x_hermes_eval_buffer(
          self.0,
          buf.as_ptr(),
          buf.len(),
          url.as_ptr(),
          &mut ok,
        )
      };
      if ok == 0 || slot < 0 {
        return None;
      }
      // Two-pass: ask for the length (cap=0), then copy.
      let need = unsafe { v8x_hermes_value_to_utf8(self.0, slot, std::ptr::null_mut(), 0) };
      if need == usize::MAX {
        return None;
      }
      let mut out = vec![0u8; need];
      let n = unsafe {
        v8x_hermes_value_to_utf8(self.0, slot, out.as_mut_ptr() as *mut c_char, need)
      };
      if n == usize::MAX {
        return None;
      }
      out.truncate(n.min(need));
      Some(String::from_utf8_lossy(&out).into_owned())
    }
  }

  impl Drop for Rt {
    fn drop(&mut self) {
      unsafe { v8x_hermes_runtime_free(self.0) };
    }
  }

  /// `HermesRuntime::isHermesBytecode`: does `data` start with the HBC magic
  /// + a well-formed header? Static check, needs no runtime instance.
  pub fn is_hermes_bytecode(data: &[u8]) -> bool {
    unsafe { v8x_hermes_is_hbc(data.as_ptr(), data.len()) != 0 }
  }
}

// Shared, PROCESS-WIDE V8 platform/init guard for every test module below.
// `v8::V8::initialize_platform`/`initialize` gate a single global state
// machine (Uninitialized -> PlatformInitialized -> Initialized) shared across
// the whole test binary; calling either a second time from an independent
// `Once` (e.g. one per test module) panics with "Invalid global state". So
// every hermes test module that needs a live isolate must call through this
// one shared `Once`, not declare its own.
#[cfg(all(test, feature = "link_hermes"))]
fn init_v8_once() {
  use crate as v8;
  use std::sync::Once;
  static START: Once = Once::new();
  START.call_once(|| {
    let platform = v8::new_default_platform(0, false).make_shared();
    v8::V8::initialize_platform(platform);
    v8::V8::initialize();
  });
}

// C3: drive the vendored v8x Rust surface (Isolate -> HandleScope -> Context
// -> String -> Script::compile -> Script::run -> read string) end to end on a
// real Hermes runtime, through the v8__* symbols in `core`. This is the
// hello-world proof that a script runs THROUGH the hermes backend, not just
// through the standalone eval shim. See
// docs/hermes-spike/experiments/C3-hermes-helloworld.md.
#[cfg(all(test, feature = "link_hermes"))]
mod hello_world {
  use crate as v8;
  use super::init_v8_once;

  #[test]
  fn hermes_backend_runs_hello_world() {
    init_v8_once();

    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);

    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let source =
      v8::String::new(scope, "'hello' + ' ' + 'world'").unwrap();
    let script = v8::Script::compile(scope, source, None).unwrap();
    let result = script.run(scope).unwrap();
    let result = result.to_rust_string_lossy(scope);

    println!("hermes backend ran: 'hello' + ' ' + 'world' = {result:?}");
    assert_eq!(result, "hello world", "real Hermes should produce 'hello world'");
  }
}

// C4: de-risk object identity, the deepest known blocker for a Hermes v8x
// backend. JSI hands out no raw pointer, so two Locals (handle-table slot
// indices) obtained for the SAME JS object are different tagged pointers.
// This proves (1) the problem is real, (2) v8__Value__StrictEquals/SameValue
// correctly reroute through JSI's own object identity instead of slot
// identity, and (3) v8__Object__GetIdentityHash returns a STABLE per-object
// hash via a hidden, non-enumerable property, invisible to ordinary JS
// enumeration. See docs/hermes-spike/experiments/C4-hermes-identity.md.
#[cfg(all(test, feature = "link_hermes"))]
mod hermes_identity {
  use crate as v8;
  use super::init_v8_once;

  fn eval<'s>(
    scope: &mut v8::PinScope<'s, '_>,
    src: &str,
  ) -> v8::Local<'s, v8::Value> {
    let source = v8::String::new(scope, src).unwrap();
    let script = v8::Script::compile(scope, source, None).unwrap();
    script.run(scope).unwrap()
  }

  #[test]
  fn hermes_identity() {
    init_v8_once();

    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    // Stash one real JS object on the global object, so it can be read back
    // through two INDEPENDENT eval calls -> two independent handle-table
    // slots for the exact same underlying JS heap object.
    eval(scope, "globalThis.o = { marker: 'same-object' };");
    eval(scope, "globalThis.p = { marker: 'different-object' };");

    let o_first = eval(scope, "globalThis.o");
    let o_second = eval(scope, "globalThis.o");
    let p = eval(scope, "globalThis.p");

    assert!(o_first.is_object(), "globalThis.o should be a JS object");
    assert!(o_second.is_object(), "globalThis.o should be a JS object");
    assert!(p.is_object(), "globalThis.p should be a JS object");

    // ---- Point 1: DEMONSTRATE the problem ---------------------------------
    // Two Locals to the SAME JS object are different handle-table slots, so
    // their tagged pointers differ. A naive port of V8 identity (raw pointer
    // equality on Local<Value>/Local<Object>) would therefore wrongly call
    // these "different objects".
    let ptr_first = &*o_first as *const v8::Value;
    let ptr_second = &*o_second as *const v8::Value;
    println!(
      "hermes_identity: two Locals to globalThis.o -> tagged pointers {:p} vs {:p} (differ: {})",
      ptr_first, ptr_second, ptr_first != ptr_second
    );
    assert_ne!(
      ptr_first, ptr_second,
      "two independently-evaluated Locals to the same JS object must be \
       different handle-table slots (this IS the problem C4 de-risks)"
    );

    // ---- Point 2: STRICT EQUALITY over JSI identity, not slot identity -----
    // v8__Value__StrictEquals must reroute through jsi::Value::strictEquals
    // (the underlying JS object identity), not the differing slot pointers.
    assert!(
      o_first.strict_equals(o_second),
      "StrictEquals must recognize two Locals to the same object as === \
       (routes through jsi::Runtime::strictEquals, not slot-pointer identity)"
    );
    assert!(
      !o_first.strict_equals(p),
      "StrictEquals must correctly distinguish two DIFFERENT objects"
    );
    assert!(o_first.same_value(o_second), "SameValue: same object -> true");
    assert!(!o_first.same_value(p), "SameValue: different objects -> false");
    println!(
      "hermes_identity: StrictEquals(o,o)={} StrictEquals(o,p)={}",
      o_first.strict_equals(o_second),
      o_first.strict_equals(p)
    );

    // ---- Point 3: STABLE IDENTITY HASH (the crux) --------------------------
    let obj_first = o_first.to_object(scope).unwrap();
    let obj_second = o_second.to_object(scope).unwrap();
    let obj_p = p.to_object(scope).unwrap();

    let hash_first = obj_first.get_identity_hash();
    let hash_second = obj_second.get_identity_hash();
    let hash_p = obj_p.get_identity_hash();
    println!(
      "hermes_identity: GetIdentityHash(o via slot A)={hash_first} \
       GetIdentityHash(o via slot B)={hash_second} GetIdentityHash(p)={hash_p}"
    );

    assert_eq!(
      hash_first, hash_second,
      "GetIdentityHash must be STABLE: the same object read back through \
       two different Locals/slots must yield the same hash"
    );
    assert_ne!(
      hash_first, hash_p,
      "GetIdentityHash must distinguish two different objects"
    );

    // Calling it again must still be stable (not re-assigned on every call).
    let obj_first_again = eval(scope, "globalThis.o").to_object(scope).unwrap();
    assert_eq!(
      obj_first_again.get_identity_hash(),
      hash_first,
      "GetIdentityHash must remain stable across repeated reads of the same object"
    );

    // ---- The hidden id must be invisible to ordinary JS enumeration --------
    let keys_of_o = eval(scope, "JSON.stringify(Object.keys(globalThis.o))")
      .to_rust_string_lossy(scope);
    let json_of_o =
      eval(scope, "JSON.stringify(globalThis.o)").to_rust_string_lossy(scope);
    let for_in_count = eval(
      scope,
      "(function(){ let n = 0; for (const k in globalThis.o) n++; return String(n); })()",
    )
    .to_rust_string_lossy(scope);
    let own_symbols =
      eval(scope, "String(Object.getOwnPropertySymbols(globalThis.o).length)")
        .to_rust_string_lossy(scope);

    println!(
      "hermes_identity: Object.keys={keys_of_o} JSON.stringify={json_of_o} \
       for-in-count={for_in_count} getOwnPropertySymbols.length={own_symbols}"
    );

    assert_eq!(
      keys_of_o, r#"["marker"]"#,
      "the hidden identity-hash slot must not appear in Object.keys"
    );
    assert_eq!(
      json_of_o,
      r#"{"marker":"same-object"}"#,
      "the hidden identity-hash slot must not appear in JSON.stringify"
    );
    assert_eq!(
      for_in_count, "1",
      "the hidden identity-hash slot must not appear in for-in"
    );
    // Object.getOwnPropertySymbols DOES see the hidden Symbol key by design
    // (Symbol-keyed props are only invisible to *enumerable-string*
    // enumeration, never to explicit reflection); assert it is non-
    // enumerable there too, which is the actual "fully hidden" guarantee.
    assert_eq!(
      own_symbols, "1",
      "the hidden id IS a real Symbol-keyed own property (only invisible to \
       string-keyed/enumerable enumeration, not to explicit reflection)"
    );
    let symbol_is_enumerable = eval(
      scope,
      "(function(){ const s = Object.getOwnPropertySymbols(globalThis.o)[0]; \
       return String(Object.getOwnPropertyDescriptor(globalThis.o, s).enumerable); })()",
    )
    .to_rust_string_lossy(scope);
    assert_eq!(
      symbol_is_enumerable, "false",
      "the hidden identity-hash property must be installed non-enumerable"
    );

    println!(
      "hermes_identity: PASS - StrictEquals/SameValue and GetIdentityHash both \
       reroute through JSI object identity, not slot identity; hidden id \
       invisible to Object.keys/JSON.stringify/for-in and non-enumerable"
    );
  }
}

// E4: v8::Private. A `Private` is a hidden Symbol used as a non-enumerable
// property key. deno_core's error machinery stores callsite metadata on thrown
// errors via `Object::set_private`/`get_private`; without a real Private the
// error formatter panics. This test proves the backend implements the full
// Private contract: ForApi is interned (same Symbol per name, distinct across
// names), set/get/has/delete round-trip, and the private key never surfaces in
// ordinary string-keyed enumeration.
#[cfg(all(test, feature = "link_hermes"))]
mod hermes_private {
  use crate as v8;
  use super::init_v8_once;

  fn eval<'s>(
    scope: &mut v8::PinScope<'s, '_>,
    src: &str,
  ) -> v8::Local<'s, v8::Value> {
    let source = v8::String::new(scope, src).unwrap();
    let script = v8::Script::compile(scope, source, None).unwrap();
    script.run(scope).unwrap()
  }

  #[test]
  fn hermes_private() {
    init_v8_once();

    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    // ---- ForApi is interned by name ------------------------------------
    let name_a = v8::String::new(scope, "Class#meta").unwrap();
    let name_b = v8::String::new(scope, "Class#other").unwrap();
    let p_a1 = v8::Private::for_api(scope, Some(name_a));
    let name_a_again = v8::String::new(scope, "Class#meta").unwrap();
    let p_a2 = v8::Private::for_api(scope, Some(name_a_again));
    let p_b = v8::Private::for_api(scope, Some(name_b));

    // Two ForApi lookups for the same name yield the SAME private symbol; a
    // different name yields a different one. Compare by using them as keys:
    // a value set under p_a1 must be readable via p_a2 but not via p_b.
    let obj = v8::Object::new(scope);
    let val = v8::Integer::new(scope, 42).into();
    assert_eq!(
      obj.set_private(scope, p_a1, val),
      Some(true),
      "set_private must succeed"
    );
    let got_via_a2 = obj.get_private(scope, p_a2).unwrap();
    assert!(
      got_via_a2.is_number() && got_via_a2.number_value(scope).unwrap() == 42.0,
      "ForApi(name) must be interned: a value set under one ForApi handle is \
       readable under another ForApi handle for the SAME name"
    );
    let got_via_b = obj.get_private(scope, p_b).unwrap();
    assert!(
      got_via_b.is_undefined(),
      "a DIFFERENT ForApi name must not read the value (distinct symbols)"
    );

    // ---- has / delete round-trip --------------------------------------
    assert_eq!(
      obj.has_private(scope, p_a1),
      Some(true),
      "has_private must see the set key"
    );
    assert_eq!(
      obj.has_private(scope, p_b),
      Some(false),
      "has_private must be false for an unset key"
    );
    assert_eq!(
      obj.delete_private(scope, p_a2),
      Some(true),
      "delete_private must succeed"
    );
    assert_eq!(
      obj.has_private(scope, p_a1),
      Some(false),
      "after delete, has_private must be false"
    );
    assert!(
      obj.get_private(scope, p_a1).unwrap().is_undefined(),
      "after delete, get_private must read undefined"
    );

    // ---- New is a FRESH (non-interned) symbol --------------------------
    let fresh_name = v8::String::new(scope, "Class#meta").unwrap();
    let p_new = v8::Private::new(scope, Some(fresh_name));
    let str_val = v8::String::new(scope, "brand").unwrap().into();
    obj.set_private(scope, p_new, str_val);
    // A ForApi handle with the SAME description must NOT collide with a New()
    // symbol (New is a distinct, unregistered Symbol).
    let p_forapi_same = {
      let n = v8::String::new(scope, "Class#meta").unwrap();
      v8::Private::for_api(scope, Some(n))
    };
    assert!(
      obj.get_private(scope, p_forapi_same).unwrap().is_undefined(),
      "Private::New must be a distinct symbol from a same-named ForApi"
    );

    // ---- the private key is invisible to string-keyed enumeration ------
    // Stash the object on the global and set a private + a normal property,
    // then confirm Object.keys / JSON only surface the normal one.
    let global = context.global(scope);
    let key = v8::String::new(scope, "probe").unwrap();
    global.set(scope, key.into(), obj.into());
    let public_key = v8::String::new(scope, "visible").unwrap();
    let one = v8::Integer::new(scope, 1).into();
    obj.set(scope, public_key.into(), one);
    let keys = eval(scope, "JSON.stringify(Object.keys(globalThis.probe))")
      .to_rust_string_lossy(scope);
    assert_eq!(
      keys, r#"["visible"]"#,
      "a private (Symbol) key must never appear in Object.keys"
    );

    // ---- Private::Name returns the description -------------------------
    let named = {
      let n = v8::String::new(scope, "desc#here").unwrap();
      v8::Private::new(scope, Some(n))
    };
    let desc = named.name(scope).to_rust_string_lossy(scope);
    assert_eq!(desc, "desc#here", "Private::Name must return the description");

    println!(
      "hermes_private: PASS - ForApi interned by name, set/get/has/delete \
       round-trip, New is distinct, private key hidden from Object.keys, Name \
       returns description"
    );
  }
}

// E4: TypedArray / ArrayBufferView ABI. deno_core's op layer marshals a
// JS-created Uint8Array into a Rust slice by checking IsArrayBufferView /
// IsUint8Array and reading ByteOffset / ByteLength / the backing ArrayBuffer;
// these were null stubs, so `op_encoding_encode_into` rejected every JS typed
// array with "expected ArrayBuffer or ArrayBufferView". This test proves the
// predicates classify correctly and the bytes read back exactly, including a
// non-zero byteOffset subarray (the interesting case for aliasing).
#[cfg(all(test, feature = "link_hermes"))]
mod hermes_typed_array {
  use crate as v8;
  use super::init_v8_once;

  fn eval<'s>(
    scope: &mut v8::PinScope<'s, '_>,
    src: &str,
  ) -> v8::Local<'s, v8::Value> {
    let source = v8::String::new(scope, src).unwrap();
    let script = v8::Script::compile(scope, source, None).unwrap();
    script.run(scope).unwrap()
  }

  #[test]
  fn hermes_typed_array_abi() {
    init_v8_once();

    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    // A plain Uint8Array [10,20,30,40,50].
    let ta = eval(scope, "new Uint8Array([10,20,30,40,50])");
    assert!(ta.is_array_buffer_view(), "Uint8Array is an ArrayBufferView");
    assert!(ta.is_typed_array(), "Uint8Array is a TypedArray");
    assert!(ta.is_uint8_array(), "Uint8Array is a Uint8Array");
    assert!(!ta.is_array_buffer(), "a view is not itself an ArrayBuffer");

    // A non-typed-array must classify false.
    let obj = eval(scope, "({})");
    assert!(!obj.is_array_buffer_view(), "a plain object is not a view");
    assert!(!obj.is_uint8_array(), "a plain object is not a Uint8Array");

    let view: v8::Local<v8::ArrayBufferView> = ta.try_into().unwrap();
    assert_eq!(view.byte_offset(), 0, "full view starts at offset 0");
    assert_eq!(view.byte_length(), 5, "5 bytes");

    // Read the bytes back via CopyContents (deno's marshalling path).
    let mut buf = [0u8; 5];
    let n = view.copy_contents(&mut buf);
    assert_eq!(n, 5, "copy_contents must report 5 bytes");
    assert_eq!(buf, [10, 20, 30, 40, 50], "bytes must read back exactly");

    // The backing ArrayBuffer must be reachable and the right size.
    let ab = view.buffer(scope).unwrap();
    assert_eq!(ab.byte_length(), 5, "backing buffer is 5 bytes");

    // A subarray with a NON-ZERO byteOffset (the aliasing case): the view's
    // data pointer and byteOffset must land on the right window of the buffer.
    let sub = eval(
      scope,
      "(() => { const a = new Uint8Array([1,2,3,4,5,6,7,8]); \
        return a.subarray(3, 6); })()",
    );
    let sub_view: v8::Local<v8::ArrayBufferView> = sub.try_into().unwrap();
    assert_eq!(sub_view.byte_offset(), 3, "subarray byteOffset is 3");
    assert_eq!(sub_view.byte_length(), 3, "subarray byteLength is 3");
    let mut sbuf = [0u8; 3];
    assert_eq!(sub_view.copy_contents(&mut sbuf), 3);
    assert_eq!(sbuf, [4, 5, 6], "subarray bytes must be the [3,6) window");

    // `data()` = Buffer__Data + byteOffset must point at the subarray's first
    // byte. Read it directly to prove the offset arithmetic is correct.
    let data_ptr = sub_view.data() as *const u8;
    assert!(!data_ptr.is_null(), "data() must be non-null");
    let first = unsafe { *data_ptr };
    assert_eq!(first, 4, "data() must point at the subarray's first byte (4)");

    println!(
      "hermes_typed_array: PASS - Is{{ArrayBufferView,TypedArray,Uint8Array}} \
       classify correctly, ByteOffset/ByteLength/Buffer/CopyContents/data() \
       read JS-created typed arrays exactly (incl. non-zero byteOffset)"
    );
  }
}

// E5: v8::ValueSerializer / ValueDeserializer round-trip (structuredClone wire
// format over JSI values). Proves the same write_header -> write_value ->
// release -> read_header -> read_value flow deno_core's op_structured_clone uses
// reconstructs an equal, independent value graph for primitives, strings,
// arrays, and nested plain objects. Also proves an uncloneable value
// (a function) makes write_value return None so the op raises a DataCloneError.
#[cfg(all(test, feature = "link_hermes"))]
mod hermes_serializer {
  use crate as v8;
  use super::init_v8_once;
  use crate::ValueDeserializerHelper;
  use crate::ValueSerializerHelper;

  // Minimal delegate: no host objects / transferables (out of scope). Only
  // throw_data_clone_error is required by the trait; the defaults refuse the
  // rest, which the Hermes walk never reaches for in-scope types.
  struct Ser;
  impl v8::ValueSerializerImpl for Ser {
    fn throw_data_clone_error<'s>(
      &self,
      scope: &mut v8::PinScope<'s, '_>,
      message: v8::Local<'s, v8::String>,
    ) {
      let exc = v8::Exception::error(scope, message);
      scope.throw_exception(exc);
    }
  }

  struct Deser;
  impl v8::ValueDeserializerImpl for Deser {}

  fn eval<'s>(
    scope: &mut v8::PinScope<'s, '_>,
    src: &str,
  ) -> v8::Local<'s, v8::Value> {
    let source = v8::String::new(scope, src).unwrap();
    let script = v8::Script::compile(scope, source, None).unwrap();
    script.run(scope).unwrap()
  }

  /// Serialize `value`, then deserialize the bytes back into a fresh value.
  fn round_trip<'s>(
    scope: &mut v8::PinScope<'s, '_>,
    context: v8::Local<'s, v8::Context>,
    value: v8::Local<'s, v8::Value>,
  ) -> Option<v8::Local<'s, v8::Value>> {
    let serializer = v8::ValueSerializer::new(scope, Box::new(Ser));
    serializer.write_header();
    serializer.write_value(context, value)?;
    let bytes = serializer.release();

    let deserializer =
      v8::ValueDeserializer::new(scope, Box::new(Deser), &bytes);
    deserializer.read_header(context)?;
    deserializer.read_value(context)
  }

  #[test]
  fn hermes_value_serializer_round_trip() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    // Build the same shape the E5 probe asserts: { a: 1, b: [2, 3] }, plus a
    // string and a boolean/null/undefined mix to cover the primitive tags.
    let input = eval(
      scope,
      "({ a: 1, b: [2, 3], s: \"héllo\", t: true, n: null, u: undefined, \
        d: 3.5, nested: { x: [10, 20], y: \"z\" } })",
    );

    let cloned =
      round_trip(scope, context, input).expect("round_trip returned None");

    // The clone must be a DIFFERENT object (structured clone, not aliasing) ...
    assert!(cloned.is_object());
    assert!(
      !cloned.strict_equals(input),
      "clone must not be the same reference as the input"
    );

    // ... and deep-equal by JSON (covers a, b, s, t, n, d, nested; `undefined`
    // properties are dropped by JSON on both sides, matching V8).
    let global = context.global(scope);
    let key_in = v8::String::new(scope, "__ser_in").unwrap();
    let key_out = v8::String::new(scope, "__ser_out").unwrap();
    global.set(scope, key_in.into(), input);
    global.set(scope, key_out.into(), cloned);
    let eq = eval(
      scope,
      "JSON.stringify(globalThis.__ser_in) === \
       JSON.stringify(globalThis.__ser_out)",
    );
    assert!(
      eq.is_true(),
      "deserialized value must deep-equal the input by JSON"
    );

    // Mutating the clone must not affect the input (independent graphs).
    let mutate = eval(
      scope,
      "globalThis.__ser_out.b[0] = 99; globalThis.__ser_in.b[0]",
    );
    assert_eq!(
      mutate.to_rust_string_lossy(scope),
      "2",
      "mutating the clone must not alias the input array"
    );

    // An uncloneable value (a function) must make write_value return None so
    // the op surfaces a DataCloneError rather than silently corrupting.
    let func = eval(scope, "(function foo() {})");
    let serializer = v8::ValueSerializer::new(scope, Box::new(Ser));
    serializer.write_header();
    assert_eq!(
      serializer.write_value(context, func),
      None,
      "serializing a function must return None (uncloneable)"
    );

    println!(
      "hermes_serializer: PASS - primitives/strings/arrays/nested objects \
       round-trip and deep-equal, clone is independent, functions are refused"
    );
  }
}

// C5: parse-free AOT execution proof + measured win. Compiles JS source to
// Hermes Bytecode (HBC) ahead of time with `hermesc` (the Hermes AOT
// compiler, extracted from the `hermes-engine` npm package, see
// docs/hermes-spike/experiments/C5-hermes-hbc-aot.md), then runs the SAME
// buffer entry point (`aot::Rt::eval_buffer`) on either the JS source or the
// precompiled HBC bytes and shows they produce identical results, while
// `isHermesBytecode` correctly distinguishes the two. A second test measures
// the parse+compile time recovered by feeding HBC instead of source on a
// bootstrap-shaped chunk of JS.
#[cfg(all(test, feature = "link_hermes"))]
mod hermes_hbc {
  use super::aot::{is_hermes_bytecode, Rt};
  use std::io::Write;
  use std::process::Command;
  use std::time::{Duration, Instant};

  /// Path to the `hermesc` AOT compiler binary vendored for this spike.
  /// Extracted from the `hermes-engine` npm package (osx-bin/hermesc), which
  /// ships the SAME Hermes release (v0.11.0, HBC bytecode version 84) as the
  /// vendored `hermes.framework` runtime, so the bytecode it emits is exactly
  /// what our linked libhermes expects. See C5 doc for provenance.
  fn hermesc_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("vendor/hermes/bin/hermesc")
  }

  /// Compile `source` to Hermes Bytecode with `hermesc -emit-binary`
  /// (optionally `-O` for the optimizing pipeline) and return the raw HBC
  /// bytes. Panics with hermesc's stderr on a compile error (a compile
  /// failure here is a test-authoring bug, not a thing under test).
  fn compile_to_hbc(source: &str, optimize: bool) -> Vec<u8> {
    let dir = std::env::temp_dir().join(format!(
      "v8x-hermes-hbc-{}-{}",
      std::process::id(),
      std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_nanos()
    ));
    std::fs::create_dir_all(&dir).unwrap();
    let src_path = dir.join("in.js");
    let hbc_path = dir.join("out.hbc");
    std::fs::File::create(&src_path)
      .unwrap()
      .write_all(source.as_bytes())
      .unwrap();

    let mut cmd = Command::new(hermesc_path());
    cmd.arg("-emit-binary");
    if optimize {
      cmd.arg("-O");
    }
    cmd.arg("-out").arg(&hbc_path).arg(&src_path);
    let out = cmd.output().expect("failed to spawn hermesc");
    assert!(
      out.status.success(),
      "hermesc failed: {}",
      String::from_utf8_lossy(&out.stderr)
    );
    let hbc = std::fs::read(&hbc_path).unwrap();
    let _ = std::fs::remove_dir_all(&dir);
    hbc
  }

  #[test]
  fn hermes_hbc_runs_through_backend() {
    let source = "(function(){ return 40 + 2; })()";
    let hbc = compile_to_hbc(source, /* optimize */ true);

    // Step 3's proof, point A: isHermesBytecode must correctly classify both
    // buffers (this is exactly the sniff evaluateJavaScript relies on).
    assert!(
      is_hermes_bytecode(&hbc),
      "hermesc output must be recognized as Hermes bytecode"
    );
    assert!(
      !is_hermes_bytecode(source.as_bytes()),
      "plain JS source must NOT be recognized as Hermes bytecode"
    );
    println!(
      "hermes_hbc: isHermesBytecode(source)=false isHermesBytecode(hbc)=true \
       (source {} bytes, hbc {} bytes)",
      source.len(),
      hbc.len()
    );

    // Step 3's proof, point B: the SAME buffer-eval entry point, fed source
    // vs fed HBC, produces the SAME result. Two fresh runtimes: each must be
    // used cold, since evaluateJavaScript is a one-shot top-level eval.
    let rt_source = Rt::new();
    let from_source = rt_source
      .eval_buffer(source.as_bytes(), "source.js")
      .expect("eval of JS source should succeed");

    let rt_hbc = Rt::new();
    let from_hbc = rt_hbc
      .eval_buffer(&hbc, "hbc.js")
      .expect("eval of precompiled HBC should succeed");

    println!(
      "hermes_hbc: eval(source) = {from_source:?}, eval(hbc) = {from_hbc:?}"
    );
    assert_eq!(
      from_source, from_hbc,
      "running precompiled HBC must produce the identical result to running \
       the JS source it was compiled from"
    );
    assert_eq!(from_source, "42");
  }

  /// Generate a bootstrap-shaped chunk of JS: many small function and object
  /// definitions, mimicking a runtime bootstrap module (a few thousand tiny
  /// bindings, not one big computation), so parsing/compiling it is nontrivial
  /// work but running it is cheap. Returns the source and the number of
  /// top-level definitions generated.
  fn generate_bootstrap_shaped_js(n_defs: usize) -> String {
    let mut s = String::with_capacity(n_defs * 120);
    s.push_str("'use strict';\nvar __v8x_ns = {};\n");
    for i in 0..n_defs {
      // A small function + a small object literal + a prototype method per
      // iteration: shaped like the many tiny builtin bindings a JS runtime
      // bootstrap module defines (ops wrappers, constants, helper classes).
      s.push_str(&format!(
        "function __v8x_fn_{i}(a, b) {{ return a + b + {i}; }}\n\
         __v8x_ns.f{i} = __v8x_fn_{i};\n\
         function __v8x_Ctor_{i}(x) {{ this.x = x; this.tag = {i}; }}\n\
         __v8x_Ctor_{i}.prototype.get = function() {{ return this.x + this.tag; }};\n\
         __v8x_ns.obj{i} = {{ id: {i}, name: 'item_{i}', nested: {{ a: {i}, b: {i} * 2 }} }};\n",
      ));
    }
    s.push_str("var __v8x_total = 0;\n");
    for i in 0..n_defs {
      s.push_str(&format!(
        "__v8x_total += new __v8x_Ctor_{i}({i}).get();\n"
      ));
    }
    s.push_str("String(__v8x_total);\n");
    s
  }

  fn median(mut xs: Vec<Duration>) -> Duration {
    xs.sort();
    xs[xs.len() / 2]
  }

  #[test]
  fn hermes_hbc_parse_free_win() {
    // A few thousand tiny function/object definitions: hundreds of KB of
    // source, shaped like a runtime bootstrap module (many small bindings),
    // per the C5 mission.
    const N_DEFS: usize = 4000;
    let source = generate_bootstrap_shaped_js(N_DEFS);
    println!(
      "hermes_hbc bench: generated bootstrap-shaped JS, {} defs, {} bytes source",
      N_DEFS,
      source.len()
    );

    let hbc = compile_to_hbc(&source, /* optimize */ true);
    println!("hermes_hbc bench: hbc size = {} bytes", hbc.len());

    assert!(is_hermes_bytecode(&hbc));
    assert!(!is_hermes_bytecode(source.as_bytes()));

    const ITERS: usize = 7;
    let mut source_times = Vec::with_capacity(ITERS);
    let mut hbc_times = Vec::with_capacity(ITERS);
    let mut last_source_result = String::new();
    let mut last_hbc_result = String::new();

    for _ in 0..ITERS {
      // Cold, fresh runtime each iteration: evaluateJavaScript is a one-shot
      // top-level eval and we want the FULL parse+compile+run cost every
      // time, not amortized JIT/cache warmup across iterations.
      let rt = Rt::new();
      let t0 = Instant::now();
      last_source_result = rt
        .eval_buffer(source.as_bytes(), "bootstrap-source.js")
        .expect("source eval should succeed");
      source_times.push(t0.elapsed());
      drop(rt);

      let rt = Rt::new();
      let t0 = Instant::now();
      last_hbc_result = rt
        .eval_buffer(&hbc, "bootstrap-hbc.js")
        .expect("hbc eval should succeed");
      hbc_times.push(t0.elapsed());
      drop(rt);
    }

    assert_eq!(
      last_source_result, last_hbc_result,
      "source-run and hbc-run must compute the identical bootstrap result"
    );

    let median_source = median(source_times.clone());
    let median_hbc = median(hbc_times.clone());
    let delta = median_source.checked_sub(median_hbc).unwrap_or_default();
    let speedup = median_source.as_secs_f64() / median_hbc.as_secs_f64().max(1e-9);

    println!(
      "hermes_hbc bench [{ITERS} iters, cold runtime each]: \
       source-run median = {median_source:?}, hbc-run (parse-free) median = {median_hbc:?}, \
       delta (parse+compile recovered) = {delta:?}, speedup = {speedup:.2}x"
    );
    println!(
      "hermes_hbc bench sizes: source = {} bytes, hbc = {} bytes ({:.2}x)",
      source.len(),
      hbc.len(),
      hbc.len() as f64 / source.len() as f64
    );
    println!(
      "hermes_hbc bench raw source times: {:?}",
      source_times
    );
    println!("hermes_hbc bench raw hbc times: {:?}", hbc_times);

    assert_eq!(last_source_result, last_hbc_result);
  }
}

#[cfg(all(test, feature = "link_hermes"))]
mod tests {
  // The whole point of the spike: prove libhermes links, JSI runs, a C++
  // exception can't escape the boundary, and a value marshals back to Rust.
  #[test]
  fn hermes_smoke_eval_40_plus_2() {
    let r = super::smoke_eval("40 + 2");
    println!("hermes eval \"40 + 2\" = {r}");
    assert_eq!(r, 42, "expected Hermes to evaluate 40 + 2 to 42");
  }

  #[test]
  fn hermes_smoke_catches_js_error() {
    // A thrown JS error must be caught at the extern "C" boundary and mapped
    // to a sentinel, never unwind into Rust.
    let r = super::smoke_eval("throw new Error('boom')");
    println!("hermes eval throwing = {r}");
    assert_eq!(r, -2000, "JS error should map to the JS_ERROR sentinel");
  }
}

// C6: widen the surface past hello-world (C3) + identity (C4). These tests
// drive the vendored rusty_v8 Rust surface end to end (Object/Array/
// Number/Integer/Boolean/Function), the same way hello_world/hermes_identity
// above do, so the proof is at the v8x API level, not the raw shim level. See
// docs/hermes-spike/experiments/C6-hermes-surface.md.
#[cfg(all(test, feature = "link_hermes"))]
mod hermes_surface {
  use crate as v8;
  use super::init_v8_once;

  fn eval<'s>(
    scope: &mut v8::PinScope<'s, '_>,
    src: &str,
  ) -> v8::Local<'s, v8::Value> {
    let source = v8::String::new(scope, src).unwrap();
    let script = v8::Script::compile(scope, source, None).unwrap();
    script.run(scope).unwrap()
  }

  /// Build `{a: 1, b: "x"}` with `Object::new` + `Object::set`, read both
  /// fields back with `Object::get`, and cross-check with a JS-side
  /// `JSON.stringify` of the SAME object (proving the writes are visible to
  /// real JS code, not just to our own read-back).
  #[test]
  fn hermes_object_new_get_set() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let obj = v8::Object::new(scope);
    let key_a = v8::String::new(scope, "a").unwrap();
    let key_b = v8::String::new(scope, "b").unwrap();
    let val_1 = v8::Integer::new(scope, 1);
    let val_x = v8::String::new(scope, "x").unwrap();

    assert_eq!(obj.set(scope, key_a.into(), val_1.into()), Some(true));
    assert_eq!(obj.set(scope, key_b.into(), val_x.into()), Some(true));

    assert_eq!(obj.has(scope, key_a.into()), Some(true));
    let missing = v8::String::new(scope, "c").unwrap();
    assert_eq!(obj.has(scope, missing.into()), Some(false));

    let read_a = obj.get(scope, key_a.into()).unwrap();
    let read_b = obj.get(scope, key_b.into()).unwrap();
    assert_eq!(read_a.to_rust_string_lossy(scope), "1");
    assert_eq!(read_b.to_rust_string_lossy(scope), "x");

    // Stash the object on the global object and confirm real JS sees the
    // exact same writes (not just our own read-back path).
    let global = context.global(scope);
    let name = v8::String::new(scope, "c6_obj").unwrap();
    global.set(scope, name.into(), obj.into());
    let json = eval(scope, "JSON.stringify(c6_obj)").to_rust_string_lossy(scope);
    println!(
      "hermes_object_new_get_set: read a={:?} b={:?}, JSON.stringify(obj)={json}",
      read_a.to_rust_string_lossy(scope),
      read_b.to_rust_string_lossy(scope),
    );
    assert_eq!(json, r#"{"a":1,"b":"x"}"#);
  }

  /// Build `[10, 20, 30]` with `Array::new` + indexed `set_index`, read the
  /// length back with `Array::length`, sum the elements via indexed
  /// `get_index`, and cross-check with JS-side `Array.isArray` +
  /// `.reduce(...)` on the SAME array.
  #[test]
  fn hermes_array_new_length_indexed_get_set() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let arr = v8::Array::new(scope, 3);
    assert_eq!(arr.length(), 3);

    let v10 = v8::Integer::new(scope, 10);
    let v20 = v8::Integer::new(scope, 20);
    let v30 = v8::Integer::new(scope, 30);
    assert_eq!(arr.set_index(scope, 0, v10.into()), Some(true));
    assert_eq!(arr.set_index(scope, 1, v20.into()), Some(true));
    assert_eq!(arr.set_index(scope, 2, v30.into()), Some(true));

    let mut sum: i64 = 0;
    for i in 0..arr.length() {
      let v = arr.get_index(scope, i).unwrap();
      sum += v.to_rust_string_lossy(scope).parse::<i64>().unwrap();
    }
    println!(
      "hermes_array_new_length_indexed_get_set: length={} sum={sum}",
      arr.length()
    );
    assert_eq!(sum, 60, "10 + 20 + 30 via indexed Array gets");

    let global = context.global(scope);
    let name = v8::String::new(scope, "c6_arr").unwrap();
    global.set(scope, name.into(), arr.into());
    let js_is_array =
      eval(scope, "String(Array.isArray(c6_arr))").to_rust_string_lossy(scope);
    let js_sum = eval(scope, "String(c6_arr.reduce((a, b) => a + b, 0))")
      .to_rust_string_lossy(scope);
    println!(
      "hermes_array_new_length_indexed_get_set: JS Array.isArray={js_is_array} \
       JS reduce-sum={js_sum}"
    );
    assert_eq!(js_is_array, "true");
    assert_eq!(js_sum, "60");
  }

  /// A nested object (`{outer: {inner: 42}}`), built purely through the v8x
  /// Object surface, read back through two levels of `Object::get` AND
  /// cross-checked by a real JS script that reads the same nested path.
  #[test]
  fn hermes_nested_object() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let inner = v8::Object::new(scope);
    let key_inner_field = v8::String::new(scope, "inner").unwrap();
    let val_42 = v8::Integer::new(scope, 42);
    assert_eq!(
      inner.set(scope, key_inner_field.into(), val_42.into()),
      Some(true)
    );

    let outer = v8::Object::new(scope);
    let key_outer_field = v8::String::new(scope, "outer").unwrap();
    assert_eq!(
      outer.set(scope, key_outer_field.into(), inner.into()),
      Some(true)
    );

    let read_outer = outer.get(scope, key_outer_field.into()).unwrap();
    assert!(read_outer.is_object(), "outer.outer should read back as an object");
    let read_outer_obj = read_outer.to_object(scope).unwrap();
    let read_inner = read_outer_obj.get(scope, key_inner_field.into()).unwrap();
    let read_value = read_inner.to_rust_string_lossy(scope);
    println!("hermes_nested_object: outer.inner (read via two Object::get) = {read_value}");
    assert_eq!(read_value, "42");

    let global = context.global(scope);
    let name = v8::String::new(scope, "c6_nested").unwrap();
    global.set(scope, name.into(), outer.into());
    let json = eval(scope, "JSON.stringify(c6_nested)").to_rust_string_lossy(scope);
    println!("hermes_nested_object: JSON.stringify(nested) = {json}");
    assert_eq!(json, r#"{"outer":{"inner":42}}"#);
  }

  /// `Number`/`Integer`/`Boolean` construction and read-back, plus
  /// `Value::Is*` predicates, exercised end to end.
  #[test]
  fn hermes_number_integer_boolean_roundtrip() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let n = v8::Number::new(scope, 3.5);
    assert_eq!(n.value(), 3.5);
    let i = v8::Integer::new(scope, -7);
    assert_eq!(i.value(), -7);
    let b_true = v8::Boolean::new(scope, true);
    let b_false = v8::Boolean::new(scope, false);

    let n_val: v8::Local<v8::Value> = n.into();
    let b_val: v8::Local<v8::Value> = b_true.into();
    assert!(n_val.is_number());
    assert!(!n_val.is_boolean());
    assert!(b_val.is_boolean());
    assert!(!b_val.is_number());
    assert!(b_true.boolean_value(scope));
    assert!(!b_false.boolean_value(scope));

    println!(
      "hermes_number_integer_boolean_roundtrip: n={} i={} b_true={} b_false={}",
      n.value(),
      i.value(),
      b_true.boolean_value(scope),
      b_false.boolean_value(scope),
    );
  }

  /// Calling a JS function value via `Function::call`: define `add(a, b)` in
  /// JS, read it back as a `Local<Function>`, and call it from Rust with
  /// `Integer` arguments built on the Rust side.
  #[test]
  fn hermes_function_call() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    eval(scope, "globalThis.add = function(a, b) { return a + b; };");
    let add_val = eval(scope, "globalThis.add");
    assert!(add_val.is_function(), "globalThis.add should read back as a function");
    let add_fn: v8::Local<v8::Function> = add_val.cast();

    let a = v8::Integer::new(scope, 19);
    let b = v8::Integer::new(scope, 23);
    let undef = v8::undefined(scope);
    let result = add_fn
      .call(scope, undef.into(), &[a.into(), b.into()])
      .unwrap();
    let result_str = result.to_rust_string_lossy(scope);
    println!("hermes_function_call: add(19, 23) via Function::call = {result_str}");
    assert_eq!(result_str, "42");
  }

  /// C10: a native Rust FunctionCallback invoked when JS calls the function.
  /// Builds a function via `Function::new` whose callback echoes its first
  /// argument's length + 1000 back as the return value, installs it on the
  /// global, and calls it from JS via `eval`. Proves the full JSI-host ->
  /// Rust-callback -> ReturnValue -> JSI round trip.
  #[test]
  fn hermes_native_callback() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    fn cb(
      scope: &mut v8::PinScope,
      args: v8::FunctionCallbackArguments,
      mut rv: v8::ReturnValue<v8::Value>,
    ) {
      assert_eq!(args.length(), 1);
      let arg0 = args.get(0);
      let s = arg0.to_rust_string_lossy(scope);
      rv.set_int32(1000 + s.len() as i32);
    }

    let func = v8::Function::new(scope, cb).unwrap();
    let key = v8::String::new(scope, "nativeCb").unwrap();
    let global = context.global(scope);
    global.set(scope, key.into(), func.into());

    let result = eval(scope, "globalThis.nativeCb('hello')");
    assert!(result.is_int32(), "callback should return an int32");
    assert_eq!(result.to_rust_string_lossy(scope), "1005");
    println!("hermes_native_callback: nativeCb('hello') = 1005");
  }

  /// C11: ObjectTemplate + internal fields + a native-data-property accessor,
  /// end to end. Builds an ObjectTemplate with one internal field and a
  /// `key` getter that returns the internal field, instantiates it, sets the
  /// internal field to 42, installs the instance on the global, and confirms
  /// `obj.key === 42` from JS (through the accessor -> internal field path).
  #[test]
  fn hermes_object_template_basic() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let getter = |scope: &mut v8::PinScope,
                  _key: v8::Local<v8::Name>,
                  args: v8::PropertyCallbackArguments,
                  mut rv: v8::ReturnValue<v8::Value>| {
      let this = args.holder();
      assert!(!args.should_throw_on_error());
      let field: v8::Local<v8::Value> =
        this.get_internal_field(scope, 0).unwrap().try_into().unwrap();
      rv.set(field);
    };

    let key = v8::String::new(scope, "key").unwrap();
    let templ = v8::ObjectTemplate::new(scope);
    assert!(templ.set_internal_field_count(1));
    templ.set_accessor(key.into(), getter);

    let obj = templ.new_instance(scope).unwrap();
    assert_eq!(obj.internal_field_count(), 1);

    // Unset internal field reads back as undefined.
    let unset: v8::Local<v8::Value> =
      obj.get_internal_field(scope, 0).unwrap().try_into().unwrap();
    assert!(unset.is_undefined());

    let fortytwo = v8::Integer::new(scope, 42);
    assert!(obj.set_internal_field(0, fortytwo.into()));

    let name = v8::String::new(scope, "otObj").unwrap();
    context.global(scope).set(scope, name.into(), obj.into());
    let result = eval(scope, "otObj.key");
    assert_eq!(result.to_rust_string_lossy(scope), "42");
    println!("hermes_object_template_basic: otObj.key = 42 (via accessor -> internal field)");

    // A FunctionTemplate instance-template with an internal field, invoked via
    // `new`: the constructor callback sets the field on the receiver, and it
    // reads back through GetInternalField (matches
    // instance_template_with_internal_field).
    pub fn ctor_cb(
      scope: &mut v8::PinScope,
      args: v8::FunctionCallbackArguments,
      mut retval: v8::ReturnValue<v8::Value>,
    ) {
      let this = args.this();
      assert!(this.set_internal_field(0, v8::Integer::new(scope, 42).into()));
      retval.set(this.into());
    }
    let ctor_templ = v8::FunctionTemplate::new(scope, ctor_cb);
    ctor_templ.instance_template(scope).set_internal_field_count(1);
    let cn = v8::String::new(scope, "WIF").unwrap();
    let cf = ctor_templ.get_function(scope).unwrap();
    context.global(scope).set(scope, cn.into(), cf.into());
    let made = eval(scope, "new WIF()");
    let field: v8::Local<v8::Value> = made
      .to_object(scope)
      .unwrap()
      .get_internal_field(scope, 0)
      .unwrap()
      .try_into()
      .unwrap();
    assert_eq!(field.integer_value(scope).unwrap(), 42);
    println!("hermes_object_template_basic: new WIF() internal field = 42");
  }

  /// C12: `Signature` receiver check, end to end (mirrors
  /// `function_template_signature`). `templ0`'s function `C` has no
  /// signature; `templ1`'s function `f` is built with a signature targeting
  /// `templ0`. `f.call(new C)` (a receiver constructed by `templ0`) must
  /// succeed; `f.call(new Object)` (an unrelated receiver) must throw
  /// "Illegal invocation".
  #[test]
  fn hermes_function_template_signature() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);

    fn fortytwo_cb(
      _scope: &mut v8::PinScope,
      _args: v8::FunctionCallbackArguments,
      mut rv: v8::ReturnValue<v8::Value>,
    ) {
      rv.set_int32(42);
    }

    let templ0 = v8::FunctionTemplate::new(scope, fortytwo_cb);
    let signature = v8::Signature::new(scope, templ0);
    let templ1 = v8::FunctionTemplate::builder(fortytwo_cb)
      .signature(signature)
      .build(scope);

    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);
    v8::tc_scope!(let scope, scope);

    let global = context.global(scope);
    let name = v8::String::new(scope, "C").unwrap();
    let value = templ0.get_function(scope).unwrap();
    global.set(scope, name.into(), value.into()).unwrap();
    let name = v8::String::new(scope, "f").unwrap();
    let value = templ1.get_function(scope).unwrap();
    global.set(scope, name.into(), value.into()).unwrap();

    fn run<'s>(
      scope: &mut v8::PinScope<'s, '_>,
      src: &str,
    ) -> Option<v8::Local<'s, v8::Value>> {
      let source = v8::String::new(scope, src).unwrap();
      let script = v8::Script::compile(scope, source, None).unwrap();
      script.run(scope)
    }

    let ok = run(scope, "f.call(new C)");
    assert!(ok.is_some(), "f.call(new C) should succeed");
    assert!(!scope.has_caught());
    println!(
      "hermes_function_template_signature: f.call(new C) = {:?}",
      ok.map(|v| v.integer_value(scope))
    );

    let bad = run(scope, "f.call(new Object)");
    println!("hermes_function_template_signature: f.call(new Object) is_none={}", bad.is_none());
    println!("hermes_function_template_signature: has_caught={}", scope.has_caught());
    if let Some(exc) = scope.exception() {
      let msg = exc.to_rust_string_lossy(scope);
      println!("hermes_function_template_signature: f.call(new Object) threw {msg:?}");
    }
    assert!(bad.is_none(), "f.call(new Object) should throw");
    assert!(scope.has_caught());
    let msg = scope.exception().unwrap().to_rust_string_lossy(scope);
    assert!(msg.contains("Illegal invocation"), "unexpected message: {msg}");
  }

  /// `JSON.stringify` run as a script that reads back a value built entirely
  /// through the v8x Object/Array/primitive surface (not constructed as a
  /// JS-source literal), proving the C++-side writes are indistinguishable
  /// from a real JS-authored object to Hermes's own JSON implementation.
  #[test]
  fn hermes_json_stringify_of_native_built_value() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let obj = v8::Object::new(scope);
    let key_list = v8::String::new(scope, "list").unwrap();
    let key_ok = v8::String::new(scope, "ok").unwrap();

    let arr = v8::Array::new(scope, 2);
    let e0 = v8::Integer::new(scope, 1);
    let e1 = v8::Integer::new(scope, 2);
    arr.set_index(scope, 0, e0.into());
    arr.set_index(scope, 1, e1.into());

    let ok = v8::Boolean::new(scope, true);

    obj.set(scope, key_list.into(), arr.into());
    obj.set(scope, key_ok.into(), ok.into());

    let global = context.global(scope);
    let name = v8::String::new(scope, "c6_json_target").unwrap();
    global.set(scope, name.into(), obj.into());

    let json = eval(scope, "JSON.stringify(c6_json_target)")
      .to_rust_string_lossy(scope);
    println!("hermes_json_stringify_of_native_built_value: {json}");
    assert_eq!(json, r#"{"list":[1,2],"ok":true}"#);
  }
}

// D0: Deno boot recon probe. These tests walk the boot-critical v8 subsystems
// in dependency order (isolate+context, then Promise, then microtask queue,
// then ES module instantiate+evaluate) using the SAME vendored rusty_v8 Rust
// surface deno_core drives. Each test isolates one subsystem so a failure names
// exactly which v8__* wall deno_core would hit at that stage. `boot_baseline`
// is expected to PASS today (it is the surface C6 already proved); the async +
// module probes are expected to FAIL today and mark the first walls to Deno
// boot. See docs/hermes-spike/experiments/D0-deno-boot-recon.md.
#[cfg(all(test, feature = "link_hermes"))]
mod hermes_boot_probe {
  use crate as v8;
  use super::init_v8_once;

  /// Stage 0: isolate + context + trivial classic-script execution. This is the
  /// minimum `JsRuntime::new` + `execute_script("1 + 1")` boot path (no
  /// snapshot, no modules, no async). Expected to PASS: it is the C3/C6 surface.
  #[test]
  fn boot_baseline_isolate_context_script() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let source = v8::String::new(scope, "1 + 1").unwrap();
    let script = v8::Script::compile(scope, source, None)
      .expect("Script::compile of '1 + 1'");
    let result = script.run(scope).expect("Script::run of '1 + 1'");
    assert_eq!(result.to_rust_string_lossy(scope), "2");
  }

  /// Stage 1a: Promise resolver round trip. deno_core creates a resolver per
  /// pending op, resolves it, and reads the promise state back. WALL if
  /// `v8__Promise__Resolver__New` / `GetPromise` / `Resolve` / `State` are stubs.
  #[test]
  fn boot_promise_resolver_roundtrip() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let resolver = v8::PromiseResolver::new(scope)
      .expect("PromiseResolver::new returned None (v8__Promise__Resolver__New is a stub)");
    let promise = resolver.get_promise(scope);
    assert_eq!(
      promise.state(),
      v8::PromiseState::Pending,
      "fresh promise should be Pending"
    );

    let val = v8::Integer::new(scope, 42);
    resolver
      .resolve(scope, val.into())
      .expect("PromiseResolver::resolve returned None (stub)");
    assert_eq!(
      promise.state(),
      v8::PromiseState::Fulfilled,
      "promise should be Fulfilled after resolve"
    );
    let result = promise.result(scope);
    assert_eq!(result.to_rust_string_lossy(scope), "42");
  }

  /// Stage 1b: microtask enqueue + checkpoint. deno_core relies on the
  /// microtask checkpoint to drain `.then` callbacks and settle resolved
  /// promises after each op batch. WALL if `EnqueueMicrotask` /
  /// `PerformMicrotaskCheckpoint` do not actually run the queued function.
  #[test]
  fn boot_microtask_enqueue_and_checkpoint() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    // A microtask that sets a global flag; after the checkpoint the flag must
    // be observable to JS. Uses a JS closure so we do not need a Rust callback.
    let setup = v8::String::new(
      scope,
      "globalThis.__mt_ran = false; \
       globalThis.__mt = function () { globalThis.__mt_ran = true; };",
    )
    .unwrap();
    let script = v8::Script::compile(scope, setup, None).unwrap();
    script.run(scope).unwrap();

    let global = context.global(scope);
    let name = v8::String::new(scope, "__mt").unwrap();
    let mt = global.get(scope, name.into()).unwrap();
    let mt_fn = v8::Local::<v8::Function>::try_from(mt)
      .expect("__mt should be a Function");

    scope.enqueue_microtask(mt_fn);
    scope.perform_microtask_checkpoint();

    let flag = v8::String::new(scope, "__mt_ran").unwrap();
    let ran = global.get(scope, flag.into()).unwrap();
    assert_eq!(
      ran.to_rust_string_lossy(scope),
      "true",
      "microtask did not run (PerformMicrotaskCheckpoint is a no-op stub)"
    );
  }

  /// E5 regression: a plain JS-created promise (`Promise.resolve().then(...)`,
  /// never routed through PromiseResolver::new/record) must report its settled
  /// state on the FIRST `Promise::State()` read after a microtask checkpoint,
  /// with no pre-arming read. V8's `Promise::State` reflects `[[PromiseState]]`
  /// synchronously; our WeakMap recorder is armed lazily, so without the
  /// drain-and-re-read in `v8x_hermes_promise_state` this promise read Pending
  /// forever (the E5 "plain-promise stays Pending" wall that blocked every
  /// await-based Web API, e.g. ReadableStream reads).
  #[test]
  fn promise_then_state_settles_on_first_read_after_checkpoint() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    // A chained promise created entirely in JS; it never passes through our
    // PromiseResolver machinery, so it has no WeakMap entry until first queried.
    let setup = v8::String::new(
      scope,
      "globalThis.__p = Promise.resolve(7).then(function (v) { return v + 1; });",
    )
    .unwrap();
    let script = v8::Script::compile(scope, setup, None).unwrap();
    script.run(scope).unwrap();

    // Drive the event loop exactly as deno_core does: a checkpoint drains the
    // chained reaction so the promise settles to 8.
    scope.perform_microtask_checkpoint();

    let global = context.global(scope);
    let name = v8::String::new(scope, "__p").unwrap();
    let p_val = global.get(scope, name.into()).unwrap();
    let promise = v8::Local::<v8::Promise>::try_from(p_val)
      .expect("__p should be a Promise");

    // FIRST state read: must observe Fulfilled, not Pending (the bug).
    assert_eq!(
      promise.state(),
      v8::PromiseState::Fulfilled,
      "chained JS promise must report Fulfilled on the first state read after \
       a checkpoint (E5 plain-promise-stays-Pending regression)"
    );
    let result = promise.result(scope);
    assert_eq!(
      result.to_rust_string_lossy(scope),
      "8",
      "chained .then result should be 8"
    );
  }

  /// Stage 2: ES module compile + instantiate + evaluate. deno_core evaluates
  /// user code and (in some boot configs) core JS as ES modules. WALL if
  /// `v8__ScriptCompiler__CompileModule` / `v8__Module__InstantiateModule` /
  /// `v8__Module__Evaluate` are stubs. A trivial module with no imports still
  /// needs a resolve callback signature but never calls it.
  #[test]
  fn boot_es_module_instantiate_evaluate() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let src = v8::String::new(scope, "globalThis.__mod_ran = 7;").unwrap();
    let name = v8::String::new(scope, "probe.js").unwrap();
    let origin = v8::ScriptOrigin::new(
      scope,
      name.into(),
      0,
      0,
      false,
      0,
      None,
      false,
      false,
      true, // is_module
      None,
    );
    let mut source = v8::script_compiler::Source::new(src, Some(&origin));
    let module = v8::script_compiler::compile_module(scope, &mut source)
      .expect("compile_module returned None (v8__ScriptCompiler__CompileModule is a stub)");

    fn resolve_noop<'s>(
      _context: v8::Local<'s, v8::Context>,
      _specifier: v8::Local<'s, v8::String>,
      _import_attributes: v8::Local<'s, v8::FixedArray>,
      _referrer: v8::Local<'s, v8::Module>,
    ) -> Option<v8::Local<'s, v8::Module>> {
      None
    }

    let ok = module.instantiate_module(scope, resolve_noop);
    assert_eq!(
      ok,
      Some(true),
      "instantiate_module failed (v8__Module__InstantiateModule is a stub)"
    );
    let _ = module
      .evaluate(scope)
      .expect("Module::evaluate returned None (v8__Module__Evaluate is a stub)");

    let global = context.global(scope);
    let flag = v8::String::new(scope, "__mod_ran").unwrap();
    let ran = global.get(scope, flag.into()).unwrap();
    assert_eq!(ran.to_rust_string_lossy(scope), "7");
  }

  /// Stage 3 (D3): the op round trip end to end. deno_core binds every op as a
  /// `FunctionTemplate` whose `.data()` is a `v8::External` wrapping the op's
  /// `OpCtx` pointer; the native callback reads that External back out of
  /// `FunctionCallbackInfo::data()` to dispatch. This probe reproduces exactly
  /// that shape with ONE op: an External wrapping a sentinel pointer, a
  /// FunctionTemplate whose data is that External, installed on the global,
  /// called from JS, and the External read back inside the callback and its
  /// pointer checked against the sentinel. If this is green, the External +
  /// FunctionTemplate + FunctionCallbackInfo::data path deno_core's op glue
  /// rides on works.
  #[test]
  fn boot_op_external_roundtrip() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    // The sentinel "OpCtx" pointer the op callback must recover from its data.
    const SENTINEL: usize = 0xABCD_1234;

    fn op_cb(
      scope: &mut v8::PinScope,
      args: v8::FunctionCallbackArguments,
      mut rv: v8::ReturnValue<v8::Value>,
    ) {
      // Read the External back out of the callback data (this is how deno_core
      // recovers its OpCtx*). Return 1 iff it matches the sentinel, else 0.
      let data = args.data();
      let ext = v8::Local::<v8::External>::try_from(data)
        .expect("callback data should be an External");
      let got = ext.value() as usize;
      rv.set_int32(if got == SENTINEL { 1 } else { 0 });
      let _ = scope;
    }

    let external = v8::External::new(scope, SENTINEL as *mut std::ffi::c_void);
    let templ = v8::FunctionTemplate::builder(op_cb)
      .data(external.into())
      .build(scope);
    let func = templ.get_function(scope).unwrap();

    // SetName the op function (deno_core names every op) and read it back.
    let op_name = v8::String::new(scope, "op_probe").unwrap();
    func.set_name(op_name);
    let got_name = func.get_name(scope);
    assert_eq!(
      got_name.to_rust_string_lossy(scope),
      "op_probe",
      "Function::SetName/GetName round trip failed"
    );

    let global = context.global(scope);
    let key = v8::String::new(scope, "op_probe").unwrap();
    global.set(scope, key.into(), func.into()).unwrap();

    let src = v8::String::new(scope, "op_probe()").unwrap();
    let script = v8::Script::compile(scope, src, None).unwrap();
    let result = script.run(scope).expect("op_probe() should run");
    assert_eq!(
      result.to_rust_string_lossy(scope),
      "1",
      "op callback did not recover the External sentinel (op glue broken)"
    );

    // The extras binding object must exist, be an object, and be stable
    // (deno_core reads built-ins off it during bootstrap).
    let extras = context.get_extras_binding_object(scope);
    assert!(extras.is_object(), "extras binding should be an object");
    let extras2 = context.get_extras_binding_object(scope);
    // C4 identity: same underlying object across two calls.
    let a = v8::String::new(scope, "__extras_marker").unwrap();
    let one = v8::Integer::new(scope, 99);
    extras.set(scope, a.into(), one.into()).unwrap();
    let b = v8::String::new(scope, "__extras_marker").unwrap();
    let read = extras2.get(scope, b.into()).unwrap();
    assert_eq!(
      read.to_rust_string_lossy(scope),
      "99",
      "extras binding object identity is not stable across calls"
    );
  }

  /// Stage 4 (superseded by E1): the async-generator prototype shape. Hermes
  /// cannot PARSE `async function*`; the E1 lowering pass
  /// (`super::lower::lower_async_generators`, wired into `v8__Script__Compile`)
  /// rewrites it into a real, runnable downlevel. So this is no longer a
  /// reflection-only stub: an async-generator INSTANCE now exposes the genuine
  /// `%AsyncGeneratorPrototype%` shape (`next`/`return`/`throw`/
  /// `[Symbol.asyncIterator]`) that deno_core's primordials capture ultimately
  /// needs, and the values it produces are iterable (proven end-to-end in the
  /// `hermes_async_generator` module).
  ///
  /// Robustness note: the lowering does NOT reproduce V8's exact intrinsic
  /// identity via `Reflect.getPrototypeOf(async function*(){})` on the *function
  /// object* (that reflects the lowered wrapper, whose prototype is
  /// `Function.prototype`). The usable async-generator prototype is reached from
  /// an INSTANCE, which is what this probe asserts. See
  /// docs/hermes-spike/experiments/E1-asyncgen-lowering.md.
  #[test]
  fn boot_async_generator_primordials_capture() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    // This reproduces deno_core's ext:core/00_primordials.js %AsyncGenerator%
    // capture EXACTLY (lines 284-292): it reflects the prototype of an
    // async-generator FUNCTION OBJECT, then reads `.prototype` off it and
    // enumerates both with Reflect.ownKeys (via copyPrototype). Under the E1
    // lowering the wrapper's [[Prototype]] was Function.prototype, whose
    // `.prototype` is undefined -> primordials threw "target is not an object".
    // The E2 fix gives the lowered function a %AsyncGeneratorFunction.prototype%
    // whose `.prototype` is the real %AsyncGeneratorPrototype% (next/return/
    // throw/asyncIterator), which is what this probe asserts.
    let src = v8::String::new(
      scope,
      "const AsyncGeneratorFunc = Reflect.getPrototypeOf(async function* () {}); \
       if (typeof AsyncGeneratorFunc !== 'object' || AsyncGeneratorFunc === null) throw 'AsyncGenerator identity not an object'; \
       const proto = AsyncGeneratorFunc.prototype; \
       if (typeof proto !== 'object' || proto === null) throw 'AsyncGenerator.prototype not an object'; \
       Reflect.ownKeys(AsyncGeneratorFunc); \
       Reflect.ownKeys(proto); \
       const hasNext = typeof proto.next === 'function'; \
       const hasReturn = typeof proto.return === 'function'; \
       const hasThrow = typeof proto.throw === 'function'; \
       const hasAsyncIter = typeof proto[Symbol.asyncIterator] === 'function'; \
       const callable = typeof (async function* () {}).apply === 'function'; \
       async function* ag() {} \
       const instProto = Object.getPrototypeOf(ag()); \
       const instOk = typeof instProto.next === 'function' && typeof instProto[Symbol.asyncIterator] === 'function'; \
       (hasNext && hasReturn && hasThrow && hasAsyncIter && callable && instOk) ? 'ok' : 'bad';",
    )
    .unwrap();
    let script = v8::Script::compile(scope, src, None)
      .expect("async function* must compile after the E1 lowering");
    let result = script
      .run(scope)
      .expect("primordials-shape async-generator capture script should run without throwing");
    assert_eq!(
      result.to_rust_string_lossy(scope),
      "ok",
      "lowered async-generator function-object reflection does not match the %AsyncGenerator% shape primordials needs"
    );
  }

  /// Stage 5 (D7): Function.length reflects the declared arity. deno_core's
  /// `setUpAsyncStub` (00_infra.js) switches on `originalOp.length - 1` to pick
  /// the async-op wrapper and THROWS "Too many arguments for async op codegen"
  /// when it is wrong. Hermes host functions report `.length === 0` regardless
  /// of the paramCount handed to `createFromHostFunction`, so the backend
  /// defines an explicit non-enumerable `length` own property. This probe builds
  /// a FunctionTemplate with a declared length and asserts `fn.length` reflects
  /// it (both the plain and the constructable/template-instance path use the
  /// same C++ creation, so covering the template path covers both).
  #[test]
  fn boot_function_length_reflects_arity() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    fn cb(
      _scope: &mut v8::PinScope,
      _args: v8::FunctionCallbackArguments,
      _rv: v8::ReturnValue<v8::Value>,
    ) {
    }

    // A FunctionTemplate whose function should report length 3.
    let templ = v8::FunctionTemplate::builder(cb).length(3).build(scope);
    let func = templ.get_function(scope).unwrap();

    let global = context.global(scope);
    let key = v8::String::new(scope, "op_len_probe").unwrap();
    global.set(scope, key.into(), func.into()).unwrap();

    let src = v8::String::new(scope, "op_len_probe.length").unwrap();
    let script = v8::Script::compile(scope, src, None).unwrap();
    let result = script.run(scope).unwrap();
    assert_eq!(
      result.to_rust_string_lossy(scope),
      "3",
      "Function.length did not reflect the declared arity (setUpAsyncStub wall)"
    );
  }

  /// Stage 6 (D7): Object::with_prototype_and_properties. deno_core builds
  /// objects with a fixed prototype and an initial property set in `new_inner`
  /// (e.g. the build/version info object). WALL if
  /// `v8__Object__New__with_prototype_and_properties` is a null stub. This probe
  /// builds an object with a custom prototype carrying a method, plus two own
  /// properties, and asserts the own props read back AND the prototype method is
  /// reachable (prototype was actually set).
  #[test]
  fn boot_object_with_prototype_and_properties() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    // Build a prototype object with a `tag` property via JS.
    let proto_src = v8::String::new(scope, "({ tag: 'proto-tag' })").unwrap();
    let proto_script = v8::Script::compile(scope, proto_src, None).unwrap();
    let proto_val = proto_script.run(scope).unwrap();

    let k1 = v8::String::new(scope, "a").unwrap();
    let k2 = v8::String::new(scope, "b").unwrap();
    let names: [v8::Local<v8::Name>; 2] = [k1.into(), k2.into()];
    let v1 = v8::Integer::new(scope, 10);
    let v2 = v8::Integer::new(scope, 20);
    let values: [v8::Local<v8::Value>; 2] = [v1.into(), v2.into()];

    let obj = v8::Object::with_prototype_and_properties(
      scope, proto_val, &names, &values,
    );

    let global = context.global(scope);
    let key = v8::String::new(scope, "__wpp").unwrap();
    global.set(scope, key.into(), obj.into()).unwrap();

    // Own props readable, and the prototype's `tag` reachable through the chain.
    let src = v8::String::new(
      scope,
      "(__wpp.a === 10 && __wpp.b === 20 && __wpp.tag === 'proto-tag') \
       ? 'ok' : 'bad'",
    )
    .unwrap();
    let script = v8::Script::compile(scope, src, None).unwrap();
    let result = script.run(scope).unwrap();
    assert_eq!(
      result.to_rust_string_lossy(scope),
      "ok",
      "with_prototype_and_properties did not set own props + prototype"
    );
  }

  /// Stage 7 (D7): Value::IsPromise. deno_core reads a source module's Evaluate
  /// result as a Promise (`mod_evaluate_sync` type-checks it); the modeled D2
  /// Evaluate returns the D1 resolved promise. WALL if `v8__Value__IsPromise` is
  /// a null stub (it read as a garbage bool -> `BadType`). This probe builds a
  /// real promise via the resolver and asserts IsPromise is true for it and
  /// false for a plain object.
  #[test]
  fn boot_value_is_promise() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let resolver = v8::PromiseResolver::new(scope).unwrap();
    let promise = resolver.get_promise(scope);
    let promise_val: v8::Local<v8::Value> = promise.into();
    assert!(
      promise_val.is_promise(),
      "IsPromise should be true for a real promise (v8__Value__IsPromise stub?)"
    );

    let plain = v8::Object::new(scope);
    let plain_val: v8::Local<v8::Value> = plain.into();
    assert!(
      !plain_val.is_promise(),
      "IsPromise should be false for a plain object"
    );

    // And the try_from::<Promise> path deno_core uses must succeed.
    let back = v8::Local::<v8::Promise>::try_from(promise_val);
    assert!(
      back.is_ok(),
      "Local::<Promise>::try_from should accept a real promise"
    );
  }

  /// Stage 8 (D7): the import.meta proto flow. deno_core builds a null-prototype
  /// object via `with_prototype_and_properties(null, [], [])`, stores it in a
  /// `Global`, and later reads it back (through an op) to set `.log` on it
  /// (01_core.js). A null-prototype object must still be a settable Object, and
  /// the Global round-trip must preserve object identity. This probe reproduces
  /// exactly that: build the null-proto object, round-trip through a Global, and
  /// set a property on the recovered Local.
  #[test]
  fn boot_null_proto_object_global_roundtrip_settable() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    // Build the null-proto object in a NESTED HandleScope and keep only a
    // Global. When the nested scope pops, the object's handle-table slot is
    // truncated; a value Global must have durably pinned the value so the later
    // Local::new still yields the live object (this is the exact deno_core boot
    // bug: a stored ext_import_meta_proto read back as a non-object).
    let global_handle = {
      v8::scope!(let inner, scope);
      let null = v8::null(inner);
      let obj = v8::Object::with_prototype_and_properties(
        inner,
        null.into(),
        &[],
        &[],
      );
      assert!(obj.is_object(), "null-proto object should be an Object");
      v8::Global::new(inner, obj)
    };

    // The nested scope has popped. Recover a Local (as the op does).
    let recovered = v8::Local::new(scope, global_handle);
    assert!(
      recovered.is_object(),
      "recovered Global value must still be an Object after the scope popped \
       (v8__Global__New must pin the value durably)"
    );

    // Set `.log` on the recovered Local (as 01_core.js does).
    let obj = v8::Local::<v8::Object>::try_from(recovered)
      .expect("recovered value should be an Object");
    let key = v8::String::new(scope, "log").unwrap();
    let val = v8::Integer::new(scope, 5);
    let set_ok = obj.set(scope, key.into(), val.into());
    assert_eq!(
      set_ok,
      Some(true),
      "setting a property on a recovered null-proto object failed"
    );
    let key2 = v8::String::new(scope, "log").unwrap();
    let read = obj.get(scope, key2.into()).unwrap();
    assert_eq!(
      read.to_rust_string_lossy(scope),
      "5",
      "property set on the recovered object did not read back"
    );
  }

  /// Stage 9 (D7): an op that RETURNS a v8::Local object (via ReturnValue::Set),
  /// mirroring deno_core's `op_get_ext_import_meta_proto`. 01_core.js calls that
  /// op and immediately sets `.log` on the returned object; if the op return
  /// value does not propagate, JS sees `undefined` and throws "Cannot set
  /// property 'log' of undefined". This probe builds an op that returns a fresh
  /// object and asserts JS can set a property on the returned value.
  #[test]
  fn boot_op_returns_object_settable_from_js() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    fn op_returns_obj(
      scope: &mut v8::PinScope,
      _args: v8::FunctionCallbackArguments,
      mut rv: v8::ReturnValue<v8::Value>,
    ) {
      let obj = v8::Object::new(scope);
      rv.set(obj.into());
    }

    let templ = v8::FunctionTemplate::builder(op_returns_obj).build(scope);
    let func = templ.get_function(scope).unwrap();
    let global = context.global(scope);
    let key = v8::String::new(scope, "op_get_obj").unwrap();
    global.set(scope, key.into(), func.into()).unwrap();

    // Mirror 01_core.js: call the op, set `.log`, read it back.
    let src = v8::String::new(
      scope,
      "const o = op_get_obj(); o.log = 42; o.log",
    )
    .unwrap();
    let script = v8::Script::compile(scope, src, None).unwrap();
    let result = script
      .run(scope)
      .expect("op returning an object then setting a prop should run");
    assert_eq!(
      result.to_rust_string_lossy(scope),
      "42",
      "op did not return a usable object (ReturnValue::Set of a Local broken)"
    );
  }

  /// Stage 10 (D7): typed-array `.buffer` + view construction. 01_core.js does
  /// `const b = new Uint32Array(2); new Uint8Array(b.buffer)`. If TypedArray
  /// `.buffer` returns undefined, `new Uint8Array(undefined)` throws "Cannot
  /// convert undefined value to object". This probe reproduces exactly that.
  #[test]
  fn boot_typed_array_buffer_accessor() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let src = v8::String::new(
      scope,
      "const b = new Uint32Array(2); \
       const u8 = new Uint8Array(b.buffer); \
       (u8 instanceof Uint8Array && u8.length === 8) ? 'ok' : 'bad'",
    )
    .unwrap();
    let script = v8::Script::compile(scope, src, None)
      .expect("typed-array buffer probe should compile");
    let result = script
      .run(scope)
      .expect("new Uint8Array(typedArray.buffer) should run");
    assert_eq!(
      result.to_rust_string_lossy(scope),
      "ok",
      "TypedArray.buffer accessor is broken (01_core.js callSiteRetBuf wall)"
    );
  }

  /// Stage 11 (D7): a built-in `globalThis.console`. V8 exposes one; deno_core's
  /// 01_core.js reads `globalThis.console` and calls `ObjectKeys` on it
  /// (`wrapConsole`), so an undefined console throws "Cannot convert undefined
  /// value to object". The Hermes backend synthesizes a no-op console on the
  /// global at Context::New. This probe asserts it exists, is an object, and its
  /// keys are enumerable (ObjectKeys returns method names).
  #[test]
  fn boot_global_console_present() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let src = v8::String::new(
      scope,
      "(typeof globalThis.console === 'object' && \
        typeof globalThis.console.log === 'function' && \
        Object.keys(globalThis.console).length > 0) ? 'ok' : 'bad'",
    )
    .unwrap();
    let script = v8::Script::compile(scope, src, None).unwrap();
    let result = script.run(scope).unwrap();
    assert_eq!(
      result.to_rust_string_lossy(scope),
      "ok",
      "globalThis.console missing/empty (01_core.js wrapConsole wall)"
    );
  }
}

// E1: async-generator lowering, proven END TO END through the Hermes backend.
// Hermes' compiler rejects the `async function*` / `async *method` declaration
// syntax; the `super::lower` pass (wired into `v8__Script__Compile`) rewrites it
// into the ES2017 downlevel Hermes accepts. These tests run a real async
// generator THROUGH the backend (Script::compile -> Script::run -> pump
// microtasks -> read the resolved promise), asserting the iterated values, not
// just that the source compiles. See
// docs/hermes-spike/experiments/E1-asyncgen-lowering.md.
#[cfg(all(test, feature = "link_hermes"))]
mod hermes_async_generator {
  use crate as v8;
  use super::init_v8_once;

  /// Run `src`, then repeatedly perform microtask checkpoints until the promise
  /// stashed on `globalThis[promise_name]` settles (or the pump budget is
  /// exhausted), and return its resolved string value. Async generators drive
  /// their steps through the microtask queue, so a single checkpoint is not
  /// enough: each `yield`/`await` hop reschedules onto the queue.
  fn run_and_drain<'s>(
    scope: &mut v8::PinScope<'s, '_>,
    context: v8::Local<'s, v8::Context>,
    src: &str,
    promise_name: &str,
  ) -> String {
    let source = v8::String::new(scope, src).unwrap();
    let script = v8::Script::compile(scope, source, None)
      .expect("lowered async-generator source must compile (no 'async generators are unsupported')");
    script.run(scope).expect("async-generator script must run");

    let global = context.global(scope);
    let key = v8::String::new(scope, promise_name).unwrap();
    let promise_val = global.get(scope, key.into()).unwrap();
    let promise = v8::Local::<v8::Promise>::try_from(promise_val)
      .expect("the stashed value must be a Promise");

    // Pump microtasks until the promise leaves Pending. Async generators bounce
    // through several microtask hops (one per yield/await), so give a generous
    // fixed budget; each checkpoint drains the whole current queue.
    for _ in 0..1000 {
      if promise.state() != v8::PromiseState::Pending {
        break;
      }
      scope.perform_microtask_checkpoint();
    }
    if promise.state() == v8::PromiseState::Rejected {
      let reason = promise.result(scope).to_rust_string_lossy(scope);
      panic!("async-generator promise REJECTED: {reason}");
    }
    assert_eq!(
      promise.state(),
      v8::PromiseState::Fulfilled,
      "async-generator promise did not fulfill after pumping microtasks (state {:?})",
      promise.state()
    );
    promise.result(scope).to_rust_string_lossy(scope)
  }

  /// The headline proof: an `async function*` declaration that `yield`s a plain
  /// value, a `yield await` of a resolved Promise, and another plain value,
  /// consumed by native `for await`, produces exactly "1,2,3" when driven to
  /// completion through the backend.
  #[test]
  fn async_generator_runs_end_to_end() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let src = "\
      async function* ag(){ yield 1; yield await Promise.resolve(2); yield 3; } \
      globalThis.__ag_result = (async () => { \
        let s = []; \
        for await (const x of ag()) s.push(x); \
        return s.join(','); \
      })();";
    let got = run_and_drain(scope, context, src, "__ag_result");
    println!("hermes_async_generator: for-await over ag() = {got:?}");
    assert_eq!(got, "1,2,3", "async generator did not iterate to 1,2,3 through the backend");
  }

  /// A tougher shape deno-style code uses: `yield*` delegation to another async
  /// generator, plus object- and class-method async generators, all consumed by
  /// native `for await` (including one UNBRACED for-await body, which exercises
  /// the oxc for-await brace-normalization workaround).
  #[test]
  fn async_generator_yield_star_and_methods() {
    init_v8_once();
    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let src = "\
      async function* inner(){ yield 1; yield 2; } \
      async function* outer(){ yield* inner(); yield await Promise.resolve(3); } \
      class C { async *m(){ yield 'a'; yield await Promise.resolve('b'); } } \
      const o = { async *g(){ yield 10; } }; \
      globalThis.__ag2 = (async () => { \
        let s = []; \
        for await (const x of outer()) s.push(x); \
        for await (const x of new C().m()) s.push(x); \
        for await (const x of o.g()) s.push(x); \
        return s.join(','); \
      })();";
    let got = run_and_drain(scope, context, src, "__ag2");
    println!("hermes_async_generator: yield*/method mix = {got:?}");
    assert_eq!(
      got, "1,2,3,a,b,10",
      "yield* delegation / async-method generators did not iterate correctly through the backend"
    );
  }
}
