//! Hermes engine backend for the v8 C-ABI compat layer (spike).
//!
//! Cycle 0/1 scaffold: this module makes `cargo build --features hermes`
//! compile and link with a pure-Rust stub backend and zero Hermes dependency.
//! Every `v8__*`/`v8_inspector__*` symbol the vendored rusty_v8 surface
//! declares is defined in `shims` as an `unimplemented!()` no-arg stub
//! (auto-generated by tools/gen_hermes_shims.sh); `cppgc__*` stubs live in
//! `misc`. Nothing here runs real JavaScript yet. See
//! docs/hermes-spike/NOTES.md ("Cycle 0 - integration surface") for the plan:
//! a real backend is a clone of src/quickjs/'s arena-handle shape (Hermes JSI
//! values are NaN-boxed structs like QuickJS's `JSValue`, not JSC-style
//! pointer punning), built against Hermes's C++ JSI through an extern "C"
//! bridge.

// The real backend core (hello-world path: isolate/context/handle-scope/
// string/script) is authored against the C++/JSI bridge and therefore only
// exists when `link_hermes` links a real libhermes. Without it, the pure-Rust
// stub build keeps the auto-generated stubs for these symbols in `shims`.
#[cfg(feature = "link_hermes")]
mod core;
mod misc;
mod shims;

// Feasibility proof (C2): with `--features link_hermes`, build.rs compiles
// src/hermes/hermes_eval_shim.cpp against a real libhermes and links it. The
// extern "C" bridge below reaches jsi::Runtime::evaluateJavaScript through
// that shim. This is the go/no-go for the whole engine_hermes idea: Hermes is
// C++-only JSI, so proving a Rust -> extern "C" C++ -> real Hermes -> value
// round-trip de-risks authoring the full v8__* surface the same way. Gated on
// `link_hermes` so the default `--features hermes` stub build stays dependency
// free. See docs/hermes-spike/experiments/C2-hermes-ffi.md.
#[cfg(feature = "link_hermes")]
mod smoke {
  unsafe extern "C" {
    fn v8x_hermes_smoke_eval(src: *const std::os::raw::c_char) -> i32;
  }

  /// Evaluate `src` on a fresh HermesRuntime and return the numeric result as
  /// an `i32`. Negative sentinels (`<= -1000`) signal a non-number result, a
  /// JS error, or a C++ error caught at the boundary. `src` must be valid
  /// UTF-8 with no interior NUL.
  pub fn smoke_eval(src: &str) -> i32 {
    let c = std::ffi::CString::new(src).expect("src has interior NUL");
    // SAFETY: the shim catches every C++ exception before returning, so no
    // unwinding crosses this boundary; `c` outlives the call.
    unsafe { v8x_hermes_smoke_eval(c.as_ptr()) }
  }
}

#[cfg(feature = "link_hermes")]
pub use smoke::smoke_eval;

// C3: drive the vendored v8x Rust surface (Isolate -> HandleScope -> Context
// -> String -> Script::compile -> Script::run -> read string) end to end on a
// real Hermes runtime, through the v8__* symbols in `core`. This is the
// hello-world proof that a script runs THROUGH the hermes backend, not just
// through the standalone eval shim. See
// docs/hermes-spike/experiments/C3-hermes-helloworld.md.
#[cfg(all(test, feature = "link_hermes"))]
mod hello_world {
  use crate as v8;

  fn init_v8_once() {
    use std::sync::Once;
    static START: Once = Once::new();
    START.call_once(|| {
      let platform = v8::new_default_platform(0, false).make_shared();
      v8::V8::initialize_platform(platform);
      v8::V8::initialize();
    });
  }

  #[test]
  fn hermes_backend_runs_hello_world() {
    init_v8_once();

    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);

    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let source =
      v8::String::new(scope, "'hello' + ' ' + 'world'").unwrap();
    let script = v8::Script::compile(scope, source, None).unwrap();
    let result = script.run(scope).unwrap();
    let result = result.to_rust_string_lossy(scope);

    println!("hermes backend ran: 'hello' + ' ' + 'world' = {result:?}");
    assert_eq!(result, "hello world", "real Hermes should produce 'hello world'");
  }
}

#[cfg(all(test, feature = "link_hermes"))]
mod tests {
  // The whole point of the spike: prove libhermes links, JSI runs, a C++
  // exception can't escape the boundary, and a value marshals back to Rust.
  #[test]
  fn hermes_smoke_eval_40_plus_2() {
    let r = super::smoke_eval("40 + 2");
    println!("hermes eval \"40 + 2\" = {r}");
    assert_eq!(r, 42, "expected Hermes to evaluate 40 + 2 to 42");
  }

  #[test]
  fn hermes_smoke_catches_js_error() {
    // A thrown JS error must be caught at the extern "C" boundary and mapped
    // to a sentinel, never unwind into Rust.
    let r = super::smoke_eval("throw new Error('boom')");
    println!("hermes eval throwing = {r}");
    assert_eq!(r, -2000, "JS error should map to the JS_ERROR sentinel");
  }
}
