//! Hermes engine backend for the v8 C-ABI compat layer (spike).
//!
//! Cycle 0/1 scaffold: this module makes `cargo build --features hermes`
//! compile and link with a pure-Rust stub backend and zero Hermes dependency.
//! Every `v8__*`/`v8_inspector__*` symbol the vendored rusty_v8 surface
//! declares is defined in `shims` as an `unimplemented!()` no-arg stub
//! (auto-generated by tools/gen_hermes_shims.sh); `cppgc__*` stubs live in
//! `misc`. Nothing here runs real JavaScript yet. See
//! docs/hermes-spike/NOTES.md ("Cycle 0 - integration surface") for the plan:
//! a real backend is a clone of src/quickjs/'s arena-handle shape (Hermes JSI
//! values are NaN-boxed structs like QuickJS's `JSValue`, not JSC-style
//! pointer punning), built against Hermes's C++ JSI through an extern "C"
//! bridge.

// The real backend core (hello-world path: isolate/context/handle-scope/
// string/script) is authored against the C++/JSI bridge and therefore only
// exists when `link_hermes` links a real libhermes. Without it, the pure-Rust
// stub build keeps the auto-generated stubs for these symbols in `shims`.
#[cfg(feature = "link_hermes")]
mod core;
mod misc;
mod shims;

// Feasibility proof (C2): with `--features link_hermes`, build.rs compiles
// src/hermes/hermes_eval_shim.cpp against a real libhermes and links it. The
// extern "C" bridge below reaches jsi::Runtime::evaluateJavaScript through
// that shim. This is the go/no-go for the whole engine_hermes idea: Hermes is
// C++-only JSI, so proving a Rust -> extern "C" C++ -> real Hermes -> value
// round-trip de-risks authoring the full v8__* surface the same way. Gated on
// `link_hermes` so the default `--features hermes` stub build stays dependency
// free. See docs/hermes-spike/experiments/C2-hermes-ffi.md.
#[cfg(feature = "link_hermes")]
mod smoke {
  unsafe extern "C" {
    fn v8x_hermes_smoke_eval(src: *const std::os::raw::c_char) -> i32;
  }

  /// Evaluate `src` on a fresh HermesRuntime and return the numeric result as
  /// an `i32`. Negative sentinels (`<= -1000`) signal a non-number result, a
  /// JS error, or a C++ error caught at the boundary. `src` must be valid
  /// UTF-8 with no interior NUL.
  pub fn smoke_eval(src: &str) -> i32 {
    let c = std::ffi::CString::new(src).expect("src has interior NUL");
    // SAFETY: the shim catches every C++ exception before returning, so no
    // unwinding crosses this boundary; `c` outlives the call.
    unsafe { v8x_hermes_smoke_eval(c.as_ptr()) }
  }
}

#[cfg(feature = "link_hermes")]
pub use smoke::smoke_eval;

// Shared, PROCESS-WIDE V8 platform/init guard for every test module below.
// `v8::V8::initialize_platform`/`initialize` gate a single global state
// machine (Uninitialized -> PlatformInitialized -> Initialized) shared across
// the whole test binary; calling either a second time from an independent
// `Once` (e.g. one per test module) panics with "Invalid global state". So
// every hermes test module that needs a live isolate must call through this
// one shared `Once`, not declare its own.
#[cfg(all(test, feature = "link_hermes"))]
fn init_v8_once() {
  use crate as v8;
  use std::sync::Once;
  static START: Once = Once::new();
  START.call_once(|| {
    let platform = v8::new_default_platform(0, false).make_shared();
    v8::V8::initialize_platform(platform);
    v8::V8::initialize();
  });
}

// C3: drive the vendored v8x Rust surface (Isolate -> HandleScope -> Context
// -> String -> Script::compile -> Script::run -> read string) end to end on a
// real Hermes runtime, through the v8__* symbols in `core`. This is the
// hello-world proof that a script runs THROUGH the hermes backend, not just
// through the standalone eval shim. See
// docs/hermes-spike/experiments/C3-hermes-helloworld.md.
#[cfg(all(test, feature = "link_hermes"))]
mod hello_world {
  use crate as v8;
  use super::init_v8_once;

  #[test]
  fn hermes_backend_runs_hello_world() {
    init_v8_once();

    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);

    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    let source =
      v8::String::new(scope, "'hello' + ' ' + 'world'").unwrap();
    let script = v8::Script::compile(scope, source, None).unwrap();
    let result = script.run(scope).unwrap();
    let result = result.to_rust_string_lossy(scope);

    println!("hermes backend ran: 'hello' + ' ' + 'world' = {result:?}");
    assert_eq!(result, "hello world", "real Hermes should produce 'hello world'");
  }
}

// C4: de-risk object identity, the deepest known blocker for a Hermes v8x
// backend. JSI hands out no raw pointer, so two Locals (handle-table slot
// indices) obtained for the SAME JS object are different tagged pointers.
// This proves (1) the problem is real, (2) v8__Value__StrictEquals/SameValue
// correctly reroute through JSI's own object identity instead of slot
// identity, and (3) v8__Object__GetIdentityHash returns a STABLE per-object
// hash via a hidden, non-enumerable property, invisible to ordinary JS
// enumeration. See docs/hermes-spike/experiments/C4-hermes-identity.md.
#[cfg(all(test, feature = "link_hermes"))]
mod hermes_identity {
  use crate as v8;
  use super::init_v8_once;

  fn eval<'s>(
    scope: &mut v8::PinScope<'s, '_>,
    src: &str,
  ) -> v8::Local<'s, v8::Value> {
    let source = v8::String::new(scope, src).unwrap();
    let script = v8::Script::compile(scope, source, None).unwrap();
    script.run(scope).unwrap()
  }

  #[test]
  fn hermes_identity() {
    init_v8_once();

    let isolate = &mut v8::Isolate::new(Default::default());
    v8::scope!(let scope, isolate);
    let context = v8::Context::new(scope, Default::default());
    let scope = &mut v8::ContextScope::new(scope, context);

    // Stash one real JS object on the global object, so it can be read back
    // through two INDEPENDENT eval calls -> two independent handle-table
    // slots for the exact same underlying JS heap object.
    eval(scope, "globalThis.o = { marker: 'same-object' };");
    eval(scope, "globalThis.p = { marker: 'different-object' };");

    let o_first = eval(scope, "globalThis.o");
    let o_second = eval(scope, "globalThis.o");
    let p = eval(scope, "globalThis.p");

    assert!(o_first.is_object(), "globalThis.o should be a JS object");
    assert!(o_second.is_object(), "globalThis.o should be a JS object");
    assert!(p.is_object(), "globalThis.p should be a JS object");

    // ---- Point 1: DEMONSTRATE the problem ---------------------------------
    // Two Locals to the SAME JS object are different handle-table slots, so
    // their tagged pointers differ. A naive port of V8 identity (raw pointer
    // equality on Local<Value>/Local<Object>) would therefore wrongly call
    // these "different objects".
    let ptr_first = &*o_first as *const v8::Value;
    let ptr_second = &*o_second as *const v8::Value;
    println!(
      "hermes_identity: two Locals to globalThis.o -> tagged pointers {:p} vs {:p} (differ: {})",
      ptr_first, ptr_second, ptr_first != ptr_second
    );
    assert_ne!(
      ptr_first, ptr_second,
      "two independently-evaluated Locals to the same JS object must be \
       different handle-table slots (this IS the problem C4 de-risks)"
    );

    // ---- Point 2: STRICT EQUALITY over JSI identity, not slot identity -----
    // v8__Value__StrictEquals must reroute through jsi::Value::strictEquals
    // (the underlying JS object identity), not the differing slot pointers.
    assert!(
      o_first.strict_equals(o_second),
      "StrictEquals must recognize two Locals to the same object as === \
       (routes through jsi::Runtime::strictEquals, not slot-pointer identity)"
    );
    assert!(
      !o_first.strict_equals(p),
      "StrictEquals must correctly distinguish two DIFFERENT objects"
    );
    assert!(o_first.same_value(o_second), "SameValue: same object -> true");
    assert!(!o_first.same_value(p), "SameValue: different objects -> false");
    println!(
      "hermes_identity: StrictEquals(o,o)={} StrictEquals(o,p)={}",
      o_first.strict_equals(o_second),
      o_first.strict_equals(p)
    );

    // ---- Point 3: STABLE IDENTITY HASH (the crux) --------------------------
    let obj_first = o_first.to_object(scope).unwrap();
    let obj_second = o_second.to_object(scope).unwrap();
    let obj_p = p.to_object(scope).unwrap();

    let hash_first = obj_first.get_identity_hash();
    let hash_second = obj_second.get_identity_hash();
    let hash_p = obj_p.get_identity_hash();
    println!(
      "hermes_identity: GetIdentityHash(o via slot A)={hash_first} \
       GetIdentityHash(o via slot B)={hash_second} GetIdentityHash(p)={hash_p}"
    );

    assert_eq!(
      hash_first, hash_second,
      "GetIdentityHash must be STABLE: the same object read back through \
       two different Locals/slots must yield the same hash"
    );
    assert_ne!(
      hash_first, hash_p,
      "GetIdentityHash must distinguish two different objects"
    );

    // Calling it again must still be stable (not re-assigned on every call).
    let obj_first_again = eval(scope, "globalThis.o").to_object(scope).unwrap();
    assert_eq!(
      obj_first_again.get_identity_hash(),
      hash_first,
      "GetIdentityHash must remain stable across repeated reads of the same object"
    );

    // ---- The hidden id must be invisible to ordinary JS enumeration --------
    let keys_of_o = eval(scope, "JSON.stringify(Object.keys(globalThis.o))")
      .to_rust_string_lossy(scope);
    let json_of_o =
      eval(scope, "JSON.stringify(globalThis.o)").to_rust_string_lossy(scope);
    let for_in_count = eval(
      scope,
      "(function(){ let n = 0; for (const k in globalThis.o) n++; return String(n); })()",
    )
    .to_rust_string_lossy(scope);
    let own_symbols =
      eval(scope, "String(Object.getOwnPropertySymbols(globalThis.o).length)")
        .to_rust_string_lossy(scope);

    println!(
      "hermes_identity: Object.keys={keys_of_o} JSON.stringify={json_of_o} \
       for-in-count={for_in_count} getOwnPropertySymbols.length={own_symbols}"
    );

    assert_eq!(
      keys_of_o, r#"["marker"]"#,
      "the hidden identity-hash slot must not appear in Object.keys"
    );
    assert_eq!(
      json_of_o,
      r#"{"marker":"same-object"}"#,
      "the hidden identity-hash slot must not appear in JSON.stringify"
    );
    assert_eq!(
      for_in_count, "1",
      "the hidden identity-hash slot must not appear in for-in"
    );
    // Object.getOwnPropertySymbols DOES see the hidden Symbol key by design
    // (Symbol-keyed props are only invisible to *enumerable-string*
    // enumeration, never to explicit reflection); assert it is non-
    // enumerable there too, which is the actual "fully hidden" guarantee.
    assert_eq!(
      own_symbols, "1",
      "the hidden id IS a real Symbol-keyed own property (only invisible to \
       string-keyed/enumerable enumeration, not to explicit reflection)"
    );
    let symbol_is_enumerable = eval(
      scope,
      "(function(){ const s = Object.getOwnPropertySymbols(globalThis.o)[0]; \
       return String(Object.getOwnPropertyDescriptor(globalThis.o, s).enumerable); })()",
    )
    .to_rust_string_lossy(scope);
    assert_eq!(
      symbol_is_enumerable, "false",
      "the hidden identity-hash property must be installed non-enumerable"
    );

    println!(
      "hermes_identity: PASS - StrictEquals/SameValue and GetIdentityHash both \
       reroute through JSI object identity, not slot identity; hidden id \
       invisible to Object.keys/JSON.stringify/for-in and non-enumerable"
    );
  }
}

#[cfg(all(test, feature = "link_hermes"))]
mod tests {
  // The whole point of the spike: prove libhermes links, JSI runs, a C++
  // exception can't escape the boundary, and a value marshals back to Rust.
  #[test]
  fn hermes_smoke_eval_40_plus_2() {
    let r = super::smoke_eval("40 + 2");
    println!("hermes eval \"40 + 2\" = {r}");
    assert_eq!(r, 42, "expected Hermes to evaluate 40 + 2 to 42");
  }

  #[test]
  fn hermes_smoke_catches_js_error() {
    // A thrown JS error must be caught at the extern "C" boundary and mapped
    // to a sentinel, never unwind into Rust.
    let r = super::smoke_eval("throw new Error('boom')");
    println!("hermes eval throwing = {r}");
    assert_eq!(r, -2000, "JS error should map to the JS_ERROR sentinel");
  }
}
