#!/usr/bin/env bash
# Regenerate src/shims.rs: a no-arg link stub for every C-ABI symbol Deno
# references, EXCEPT those already implemented for real in src/jsc/init.rs.
#
# Usage: tools/gen_shims.sh            (uses /tmp/union.txt symbol list)
#        tools/gen_shims.sh syms.txt   (custom symbol list, one per line)
set -euo pipefail
cd "$(dirname "$0")/.."

SYMS="${1:-/tmp/union.txt}"
OUT=src/jsc/shims.rs

# Symbols actually DEFINED in any hand-written shim_*.rs (but NOT the generated
# shims.rs). A definition is either `extern "C" fn NAME(` or a macro invocation
# `macro!(NAME, ...)`. Matching definition positions only (not bare mentions in
# comments) avoids wrongly excluding an undefined symbol from the stub set.
P='(v8__|v8_inspector__|std__|simdutf__|cppgc__)[A-Za-z0-9_]+'
for f in src/jsc/*.rs; do
  [ "$f" = src/jsc/shims.rs ] && continue
  cat "$f" 2>/dev/null
done > /tmp/all_shim_src.txt
{
  grep -oE "extern \"C\" fn ${P}" /tmp/all_shim_src.txt | sed -E 's/.* //'
  grep -oE "!\(${P}" /tmp/all_shim_src.txt | sed -E 's/^!\(//'
} | sort -u > /tmp/implemented.txt

{
  echo "//! AUTO-GENERATED by tools/gen_shims.sh — do not edit by hand."
  echo "//! A no-arg link stub for every C-ABI symbol Deno references that is not"
  echo "//! yet implemented in shim_impl.rs. A stub hit at runtime panics."
  echo "#![allow(non_snake_case)]"
  echo
  comm -23 <(sort -u "$SYMS") /tmp/implemented.txt | while read -r sym; do
    [ -z "$sym" ] && continue
    echo "#[unsafe(no_mangle)]"
    echo "pub extern \"C\" fn ${sym}() { unimplemented!(\"${sym}\") }"
  done
} > "$OUT"

echo "stubs: $(grep -c no_mangle "$OUT"), implemented: $(wc -l < /tmp/implemented.txt)"
