#!/usr/bin/env bash
# Regenerate src/shims.rs: a no-arg link stub for every C-ABI symbol Deno
# references, EXCEPT those already implemented for real in src/shim_impl.rs.
#
# Usage: tools/gen_shims.sh            (uses /tmp/union.txt symbol list)
#        tools/gen_shims.sh syms.txt   (custom symbol list, one per line)
set -euo pipefail
cd "$(dirname "$0")/.."

SYMS="${1:-/tmp/union.txt}"
OUT=src/shims.rs

# Symbols implemented for real in any hand-written shim_*.rs (but not the
# generated shims.rs itself) — exclude from stub generation.
grep -hoE 'pub extern "C" fn [A-Za-z0-9_]+' src/shim_core.rs src/shim_impl.rs src/shim_*.rs 2>/dev/null \
  | awk '{print $NF}' | sort -u > /tmp/implemented.txt

{
  echo "//! AUTO-GENERATED by tools/gen_shims.sh — do not edit by hand."
  echo "//! A no-arg link stub for every C-ABI symbol Deno references that is not"
  echo "//! yet implemented in shim_impl.rs. A stub hit at runtime panics."
  echo "#![allow(non_snake_case)]"
  echo
  comm -23 <(sort -u "$SYMS") /tmp/implemented.txt | while read -r sym; do
    [ -z "$sym" ] && continue
    echo "#[unsafe(no_mangle)]"
    echo "pub extern \"C\" fn ${sym}() { unimplemented!(\"${sym}\") }"
  done
} > "$OUT"

echo "stubs: $(grep -c no_mangle "$OUT"), implemented: $(wc -l < /tmp/implemented.txt)"
