//! AUTO-GENERATED by tools/gen_shims.sh — do not edit by hand.
//! A no-arg link stub for every C-ABI symbol Deno references that is not
//! yet implemented in shim_impl.rs. A stub hit at runtime panics.
#![allow(non_snake_case)]

